import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'ar' | 'fr' | 'de' | 'ja';
export type Theme = 'light' | 'dark';
export type ColorTheme = 'red_brick' | 'pastel';
export type FontSize = 'small' | 'normal' | 'large' | 'xl';

export const SUPPORTED_LANGUAGES: { code: Language; label: string }[] = [
    { code: 'en', label: 'English' },
    { code: 'hi', label: 'हिंदी' },
    { code: 'es', label: 'Español' },
    { code: 'ar', label: 'العربية' },
    { code: 'fr', label: 'Français' },
    { code: 'de', label: 'Deutsch' },
    { code: 'ja', label: '日本語' },
];

interface SettingsContextType {
    theme: Theme;
    toggleTheme: () => void;
    colorTheme: ColorTheme;
    setColorTheme: (theme: ColorTheme) => void;
    currentTheme: ThemeColors;
    language: Language;
    setLanguage: (lang: Language) => void;
    fontSize: FontSize;
    setFontSize: (size: FontSize) => void;
    t: (key: string) => string;
    dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'home.welcome': 'Ignite Your Inner Joy',
        'home.subtitle': 'Boost immunity & relieve stress with expert guidance from Suman Suneja.',
        'home.test_laugh': 'Test Your Laugh',
        'nav.home': 'Home',
        'nav.videos': 'Videos',
        'nav.games': 'Games',
        'nav.coach': 'Coach',
        'nav.ask_ai': 'Ask Suman',
        'profile.title': 'Your Profile',
        'profile.subtitle': 'Customize your joy identity',
        'settings.title': 'Settings',
        'settings.dark_mode': 'Dark Mode',
        'settings.language': 'Language',
        'settings.font_size': 'Font Size',
        'streak': 'Day Streak',
        'points': 'Points',
        'level': 'Level',
        'today': 'Today',
        'save_changes': 'Save Changes',
        'sign_out': 'Sign Out',
        'daily_session': 'Daily Laughter Yoga',
        'join_session': 'Join Daily Session',
        'every_day': 'Every Day',
        'traditional_yoga': 'Traditional & Laughter Yoga',
        'join_yoga': 'Join Yoga Class',
        'mon_fri': 'Mon - Fri',
        'fun_games': 'Fun Games',
        'book_session': 'Book Session',
        'contact': 'Contact',

        // Contact
        'contact.header_title': "Let's Make Magic Happen!",
        'contact.header_subtitle': "Booking a session is the first step to a happier, healthier life.",
        'contact.whatsapp_btn': "WhatsApp Us",
        'contact.instant_reply': "Instant Reply",
        'contact.email_btn': "Send Email",
        'contact.for_enquiries': "For Enquiries",
        'contact.offerings_title': "What we offer",
        'contact.offering_1_title': "1-on-1",
        'contact.offering_1_desc': "Personal Coaching",
        'contact.offering_2_title': "Corporate",
        'contact.offering_2_desc': "Stress Relief",
        'contact.offering_3_title': "Groups",
        'contact.offering_3_desc': "Workshops",
        'contact.offering_4_title': "Retreats",
        'contact.offering_4_desc': "Wellness Days",
        'contact.youtube_btn': "Watch on YouTube",
        'contact.subscribe': "Subscribe",
        'contact.website_btn': "Visit Official Website",
        'app.developed_by': "App Developed by",

        // Profile
        'profile.display_name': "Display Name",
        'profile.enter_name_placeholder': "Enter your name",
        'profile.phone_number': "Phone Number",
        'profile.no_number': "No number linked",
        'profile.streak_power': "STREAK POWER",
        'profile.streak_power_description': "Keep your laughter streak alive to unlock exclusive badges and premium content!",
        'profile.start_today': "Start today!",
        'profile.bonus': "Bonus",
        'profile.personal_info': "Personal Info",
        'profile.edit_button': "Edit",
        'profile.link_button': "Link",

        // Games
        'games.title': "AI Laughter Lab",
        'games.subtitle_jokes': "One-Liner Joke Generator",
        'games.subtitle_joy': "Experimental Joy Generator",
        'games.tab_story': "Story",
        'games.tab_jokes': "Jokes",
        'games.tab_moods': "Moods",
        'games.speaking': "Speaking...",
        'games.writing_joke': "Writing a zinger...",
        'games.brewing_laughter': "Brewing Laughter...",
        'games.funny_mode': "Funny Mode",
        'games.ai_mode': "AI Mode",
        'games.play_real_laughter': "Play Real Laughter",
        'games.offline_voice': "Offline Voice",
        'games.input_placeholder_story': "Situation (e.g. Missed Alarm)",
        'games.input_placeholder_joke': "Topic (e.g. Cats, Boss, Coffee)",
        'games.input_placeholder_mood': "Select a mood to hear different laughter styles.",
        'games.btn_joke': "Tell Me a Joke & Laugh!",
        'games.btn_story': "Generate Joy Story",
        'games.stop_audio': "Stop Audio",
        'games.mood_giggle': "Giggle Fit",
        'games.mood_belly': "Belly Laugh",
        'games.mood_snort': "Snort Laugh",
        'games.mood_cackle': "Witchy Cackle",

        // Video Library
        'video.title': 'Video Library',
        'video.visit_channel': 'Visit Official Channel',
        'video.count_suffix': 'Videos',
        'video.tab_all': 'All Videos',
        'video.tab_favorites': 'Favorites',
        'video.tab_offline': 'Offline',
        'video.search_placeholder': 'Search videos...',
        'video.filter_all': 'All',
        'video.no_videos': 'No videos found',
        'video.now_playing': 'Now Playing',
        'video.open_app': 'Open in App',
        'video.save_offline': 'Save Offline',
        'video.saving': 'Saving...',
        'video.saved': 'Saved',
        'video.remove_confirm': 'Remove from offline library?',
        'video.saved_toast': 'Offline Video Saved',
        'video.started_toast': 'Video Session Started',
        'video.page': 'Page',
        'video.of': 'of',
        'video.category_events': 'Events',
        'video.category_corporate': 'Corporate',
        'video.category_health': 'Health',
        'video.category_exercises': 'Exercises',
        'video.category_fun': 'Fun',
        'video.category_morning': 'Morning',
        'video.category_meditation': 'Meditation',
        'video.category_stress_relief': 'Stress Relief',
        'video.category_daily': 'Daily',
        'video.category_sessions': 'Sessions',
        'video.category_seniors': 'Seniors',

        // Laughter Coach
        'coach.title': 'Laughter Coach',
        'coach.subtitle': 'Laugh loudly to get your happiness score!',
        'coach.how_was_it': 'How was it?',
        'coach.help_improve': 'Help Suman AI improve!',
        'coach.skip_feedback': 'Skip Feedback',
        'coach.start_live': 'Start Live Session',
        'coach.interactive': 'Interactive Conversation',
        'coach.quick_laugh': 'Quick 1-Min Laugh',
        'coach.guided_boost': 'Guided Energy Boost',
        'coach.analyzing': 'Analyzing Joy...',
        'coach.api_missing': 'Gemini API Key Missing!',
        'coach.offline_fallback': 'Falling back to offline mode',
        'coach.joy_score': 'Joy Score',
        'coach.ai_listening': 'AI Listening...',
        'coach.listen_laugh': 'Listen & Laugh',
        'coach.listening': 'Listening...',
        'coach.ready': 'Ready',
        'coach.rate_my_laugh': 'Rate My Laugh',
        'coach.stop_rate': 'Stop & Rate',
        'coach.energy': 'Energy',
        'coach.play_again': 'Play Again',
        'coach.offline_voice': 'Using Offline Voice (Connection Issue)',
        'coach.laughter_log': 'Laughter Log',
        'coach.clear': 'Clear',
        'coach.clear_confirm': 'Are you sure you want to clear your laughter log?',
        'coach.thanks_feedback': 'Thanks for Feedback!',
        'coach.session_completed': 'Session Completed',
        'coach.laughter_analyzed': 'Laughter Analyzed',
        'coach.mic_permission': 'Please allow microphone access to use the Coach!',
        'coach.analyze_error': "Couldn't analyze the laughter. Try again!",
        'coach.session_error': 'Unable to start session.',
        'coach.connection_lost': 'Connection lost.',
        'coach.live_unavailable': 'API Key missing. Live session unavailable.',
    },
    hi: {
        'home.welcome': 'अपनी आंतरिक खुशी को जगाएं',
        'home.subtitle': 'सुमन सुनेजा के मार्गदर्शन के साथ प्रतिरक्षा बढ़ाएं और तनाव दूर करें।',
        'home.test_laugh': 'हंसी की जांच करें',
        'nav.home': 'होम',
        'nav.videos': 'वीडियो',
        'nav.games': 'खेल',
        'nav.coach': 'कोच',
        'nav.ask_ai': 'सुमन से पूछें',
        'profile.title': 'आपकी प्रोफाइल',
        'profile.subtitle': 'अपनी पहचान को अनुकूलित करें',
        'settings.title': 'सेटिंग्स',
        'settings.dark_mode': 'डार्क मोड',
        'settings.language': 'भाषा',
        'settings.font_size': 'फ़ॉन्ट आकार',
        'streak': 'स्ट्रीक',
        'points': 'अंक',
        'level': 'स्तर',
        'today': 'आज',
        'save_changes': 'सहेजें',
        'sign_out': 'साइन आउट',
        'daily_session': 'दैनिक हास्य योग',
        'join_session': 'शामिल हों',
        'every_day': 'हर दिन',
        'traditional_yoga': 'पारंपरिक और हास्य योग',
        'join_yoga': 'योग कक्षा',
        'mon_fri': 'सोम - शुक्र',
        'fun_games': 'मजेदार खेल',
        'book_session': 'सत्र बुक करें',
        'contact': 'संपर्क',

        // Contact
        'contact.header_title': "चलो जादू करते हैं!",
        'contact.header_subtitle': "एक सत्र बुक करना एक खुशहाल, स्वस्थ जीवन की ओर पहला कदम है।",
        'contact.whatsapp_btn': "व्हाट्सएप करें",
        'contact.instant_reply': "त्वरित उत्तर",
        'contact.email_btn': "ईमेल भेजें",
        'contact.for_enquiries': "पूछताछ के लिए",
        'contact.offerings_title': "हम क्या प्रदान करते हैं",
        'contact.offering_1_title': "1-पर-1",
        'contact.offering_1_desc': "व्यक्तिगत कोचिंग",
        'contact.offering_2_title': "कॉर्पोरेट",
        'contact.offering_2_desc': "तनाव से राहत",
        'contact.offering_3_title': "समूह",
        'contact.offering_3_desc': "कार्यशालाएं",
        'contact.offering_4_title': "रिट्रीट",
        'contact.offering_4_desc': "वेलनेस डेज़",
        'contact.youtube_btn': "YouTube पर देखें",
        'contact.subscribe': "सदस्यता लें",
        'contact.website_btn': "आधिकारिक वेबसाइट पर जाएं",
        'app.developed_by': "ऐप द्वारा विकसित",

        // Profile
        'profile.display_name': "प्रदर्शन नाम",
        'profile.enter_name_placeholder': "अपना नाम दर्ज करें",
        'profile.phone_number': "फ़ोन नंबर",
        'profile.no_number': "कोई नंबर लिंक नहीं है",
        'profile.streak_power': "स्ट्रीक पावर",
        'profile.streak_power_description': "विशेष बैज और प्रीमियम सामग्री अनलॉक करने के लिए अपनी हंसी की लकीर को जीवित रखें!",
        'profile.start_today': "आज ही शुरू करें!",
        'profile.bonus': "बोनस",
        'profile.personal_info': "व्यक्तिगत जानकारी",
        'profile.edit_button': "संपादित करें",
        'profile.link_button': "लिंक",

        // Games
        'games.title': "एआई लाफ्टर लैब",
        'games.subtitle_jokes': "वन-लाइनर जोक जेनरेटर",
        'games.subtitle_joy': "प्रायोगिक जॉय जेनरेटर",
        'games.tab_story': "कहानी",
        'games.tab_jokes': "चुटकुले",
        'games.tab_moods': "मूड",
        'games.speaking': "बोल रहा हूँ...",
        'games.writing_joke': "एक चुटकुला लिख रहा हूँ...",
        'games.brewing_laughter': "हंसी बना रहा हूँ...",
        'games.funny_mode': "मजेदार मोड",
        'games.ai_mode': "एआई मोड",
        'games.play_real_laughter': "असली हंसी चलाएं",
        'games.offline_voice': "ऑफ़लाइन आवाज़",
        'games.input_placeholder_story': "स्थिति (जैसे अलार्म छूट गया)",
        'games.input_placeholder_joke': "विषय (जैसे बिल्लियाँ, बॉस, कॉफ़ी)",
        'games.input_placeholder_mood': "विभिन्न हंसी शैलियों को सुनने के लिए एक मूड चुनें।",
        'games.btn_joke': "मुझे एक चुटकुला सुनाओ और हँसो!",
        'games.btn_story': "जॉय स्टोरी जेनरेट करें",
        'games.stop_audio': "ऑडियो रोकें",
        'games.mood_giggle': "खिसियाना",
        'games.mood_belly': "पेट पकड़कर हंसना",
        'games.mood_snort': "नाक से हंसना",
        'games.mood_cackle': "चुड़ैल जैसी हंसी",

        // Video Library
        'video.title': 'वीडियो लाइब्रेरी',
        'video.visit_channel': 'आधिकारिक चैनल पर जाएं',
        'video.count_suffix': 'वीडियो',
        'video.tab_all': 'सभी वीडियो',
        'video.tab_favorites': 'पसंदीदा',
        'video.tab_offline': 'ऑफ़लाइन',
        'video.search_placeholder': 'वीडियो खोजें...',
        'video.filter_all': 'सभी',
        'video.no_videos': 'कोई वीडियो नहीं मिला',
        'video.now_playing': 'अब चल रहा है',
        'video.open_app': 'ऐप में खोलें',
        'video.save_offline': 'ऑफ़लाइन सहेजें',
        'video.saving': 'सहेज रहा है...',
        'video.saved': 'सहेजा गया',
        'video.remove_confirm': 'ऑफ़लाइन लाइब्रेरी से निकालें?',
        'video.saved_toast': 'ऑफ़लाइन वीडियो सहेजा गया',
        'video.started_toast': 'वीडियो सत्र शुरू हुआ',
        'video.page': 'पृष्ठ',
        'video.of': 'का',
        'video.category_events': 'कार्यक्रम',
        'video.category_corporate': 'कॉर्पोरेट',
        'video.category_health': 'स्वास्थ्य',
        'video.category_exercises': 'व्यायाम',
        'video.category_fun': 'मज़ा',
        'video.category_morning': 'सुबह',
        'video.category_meditation': 'ध्यान',
        'video.category_stress_relief': 'तनाव से राहत',
        'video.category_daily': 'दैनिक',
        'video.category_sessions': 'सत्र',
        'video.category_seniors': 'वरिष्ठ',

        // Laughter Coach
        'coach.title': 'हास्य कोच',
        'coach.subtitle': 'अपना खुशी स्कोर प्राप्त करने के लिए जोर से हंसें!',
        'coach.how_was_it': 'यह कैसा था?',
        'coach.help_improve': 'सुमन एआई को बेहतर बनाने में मदद करें!',
        'coach.skip_feedback': 'प्रतिक्रिया छोड़ें',
        'coach.start_live': 'लाइव सत्र शुरू करें',
        'coach.interactive': 'इंटरैक्टिव बातचीत',
        'coach.quick_laugh': 'त्वरित 1-मिनट की हंसी',
        'coach.guided_boost': 'निर्देशित ऊर्जा बूस्ट',
        'coach.analyzing': 'खुशी का विश्लेषण कर रहा है...',
        'coach.api_missing': 'जेमिनी एपीआई कुंजी गायब है!',
        'coach.offline_fallback': 'ऑफ़लाइन मोड पर वापस जा रहा है',
        'coach.joy_score': 'जॉय स्कोर',
        'coach.ai_listening': 'एआई सुन रहा है...',
        'coach.listen_laugh': 'सुनो और हंसो',
        'coach.listening': 'सुन रहा है...',
        'coach.ready': 'तैयार',
        'coach.rate_my_laugh': 'मेरी हंसी को रेट करें',
        'coach.stop_rate': 'रोकें और रेट करें',
        'coach.energy': 'ऊर्जा',
        'coach.play_again': 'फिर से खेलें',
        'coach.offline_voice': 'ऑफ़लाइन आवाज़ का उपयोग कर रहा है (कनेक्शन समस्या)',
        'coach.laughter_log': 'हंसी लॉग',
        'coach.clear': 'साफ़ करें',
        'coach.clear_confirm': 'क्या आप वाकई अपना हंसी लॉग साफ़ करना चाहते हैं?',
        'coach.thanks_feedback': 'प्रतिक्रिया के लिए धन्यवाद!',
        'coach.session_completed': 'सत्र पूरा हुआ',
        'coach.laughter_analyzed': 'हंसी का विश्लेषण किया गया',
        'coach.mic_permission': 'कोच का उपयोग करने के लिए कृपया माइक्रोफ़ोन एक्सेस की अनुमति दें!',
        'coach.analyze_error': "हंसी का विश्लेषण नहीं कर सका। पुनः प्रयास करें!",
        'coach.session_error': 'सत्र शुरू करने में असमर्थ।',
        'coach.connection_lost': 'कनेक्शन टूट गया।',
        'coach.live_unavailable': 'एपीआई कुंजी गायब है। लाइव सत्र अनुपलब्ध है।',
    },
    es: {
        'home.welcome': 'Enciende tu Alegría',
        'home.subtitle': 'Mejora la inmunidad y alivia el estrés con Suman Suneja.',
        'home.test_laugh': 'Prueba tu Risa',
        'nav.home': 'Inicio',
        'nav.videos': 'Videos',
        'nav.games': 'Juegos',
        'nav.coach': 'Entrenador',
        'nav.ask_ai': 'Pregunta Suman',
        'profile.title': 'Tu Perfil',
        'profile.subtitle': 'Personaliza tu identidad',
        'settings.title': 'Ajustes',
        'settings.dark_mode': 'Modo Oscuro',
        'settings.language': 'Idioma',
        'settings.font_size': 'Tamaño de letra',
        'streak': 'Racha',
        'points': 'Puntos',
        'level': 'Nivel',
        'today': 'Hoy',
        'save_changes': 'Guardar',
        'sign_out': 'Salir',
        'daily_session': 'Yoga de la Risa',
        'join_session': 'Unirse',
        'every_day': 'Diario',
        'traditional_yoga': 'Yoga Tradicional',
        'join_yoga': 'Unirse Clase',
        'mon_fri': 'Lun - Vie',
        'fun_games': 'Juegos',
        'book_session': 'Reservar',
        'contact': 'Contacto',

        // Contact
        'contact.header_title': "¡Hagamos Magia!",
        'contact.header_subtitle': "Reservar una sesión es el primer paso hacia una vida más feliz.",
        'contact.whatsapp_btn': "WhatsApp",
        'contact.instant_reply': "Respuesta Inmediata",
        'contact.email_btn': "Enviar Email",
        'contact.for_enquiries': "Para Consultas",
        'contact.offerings_title': "Lo que ofrecemos",
        'contact.offering_1_title': "1-a-1",
        'contact.offering_1_desc': "Coaching Personal",
        'contact.offering_2_title': "Corporativo",
        'contact.offering_2_desc': "Alivio del Estrés",
        'contact.offering_3_title': "Grupos",
        'contact.offering_3_desc': "Talleres",
        'contact.offering_4_title': "Retiros",
        'contact.offering_4_desc': "Días de Bienestar",
        'contact.youtube_btn': "Ver en YouTube",
        'contact.subscribe': "Suscribirse",
        'contact.website_btn': "Visitar Sitio Web",
        'app.developed_by': "App Desarrollada por",

        // Profile
        'profile.display_name': "Nombre",
        'profile.enter_name_placeholder': "Ingresa tu nombre",
        'profile.phone_number': "Teléfono",
        'profile.no_number': "Sin número vinculado",
        'profile.streak_power': "PODER DE RACHA",
        'profile.streak_power_description': "¡Mantén viva tu racha de risa para desbloquear insignias exclusivas y contenido premium!",
        'profile.start_today': "¡Empieza hoy!",
        'profile.bonus': "Bono",
        'profile.personal_info': "Información Personal",
        'profile.edit_button': "Editar",
        'profile.link_button': "Enlazar",

        // Games
        'games.title': "Laboratorio de Risa IA",
        'games.subtitle_jokes': "Generador de Chistes",
        'games.subtitle_joy': "Generador de Alegría",
        'games.tab_story': "Historia",
        'games.tab_jokes': "Chistes",
        'games.tab_moods': "Estados",
        'games.speaking': "Hablando...",
        'games.writing_joke': "Escribiendo broma...",
        'games.brewing_laughter': "Preparando risa...",
        'games.funny_mode': "Modo Gracioso",
        'games.ai_mode': "Modo IA",
        'games.play_real_laughter': "Reproducir Risa Real",
        'games.offline_voice': "Voz Offline",
        'games.input_placeholder_story': "Situación (ej. Alarma perdida)",
        'games.input_placeholder_joke': "Tema (ej. Gatos, Jefe, Café)",
        'games.input_placeholder_mood': "Elige un estado de ánimo.",
        'games.btn_joke': "¡Cuéntame un chiste!",
        'games.btn_story': "Generar Historia de Alegría",
        'games.stop_audio': "Detener Audio",
        'games.mood_giggle': "Risita",
        'games.mood_belly': "Carcajada",
        'games.mood_snort': "Risa con resoplido",
        'games.mood_cackle': "Risa de bruja",

        // Video Library
        'video.title': 'Biblioteca de Videos',
        'video.visit_channel': 'Visitar Canal Oficial',
        'video.count_suffix': 'Videos',
        'video.tab_all': 'Todos',
        'video.tab_favorites': 'Favoritos',
        'video.tab_offline': 'Offline',
        'video.search_placeholder': 'Buscar videos...',
        'video.filter_all': 'Todos',
        'video.no_videos': 'No se encontraron videos',
        'video.now_playing': 'Reproduciendo',
        'video.open_app': 'Abrir en App',
        'video.save_offline': 'Guardar Offline',
        'video.saving': 'Guardando...',
        'video.saved': 'Guardado',
        'video.remove_confirm': '¿Eliminar de la biblioteca offline?',
        'video.saved_toast': 'Video guardado offline',
        'video.started_toast': 'Sesión de video iniciada',
        'video.page': 'Página',
        'video.of': 'de',
        'video.category_events': 'Eventos',
        'video.category_corporate': 'Corporativo',
        'video.category_health': 'Salud',
        'video.category_exercises': 'Ejercicios',
        'video.category_fun': 'Diversión',
        'video.category_morning': 'Mañana',
        'video.category_meditation': 'Meditación',
        'video.category_stress_relief': 'Alivio del Estrés',
        'video.category_daily': 'Diario',
        'video.category_sessions': 'Sesiones',
        'video.category_seniors': 'Mayores',

        // Laughter Coach
        'coach.title': 'Entrenador de Risa',
        'coach.subtitle': '¡Ríe fuerte para obtener tu puntuación de felicidad!',
        'coach.how_was_it': '¿Cómo estuvo?',
        'coach.help_improve': '¡Ayuda a Suman AI a mejorar!',
        'coach.skip_feedback': 'Omitir',
        'coach.start_live': 'Iniciar Sesión en Vivo',
        'coach.interactive': 'Conversación Interactiva',
        'coach.quick_laugh': 'Risa Rápida 1-Min',
        'coach.guided_boost': 'Impulso de Energía Guiado',
        'coach.analyzing': 'Analizando Alegría...',
        'coach.api_missing': '¡Falta Clave API Gemini!',
        'coach.offline_fallback': 'Volviendo a modo offline',
        'coach.joy_score': 'Puntuación de Alegría',
        'coach.ai_listening': 'IA Escuchando...',
        'coach.listen_laugh': 'Escucha y Ríe',
        'coach.listening': 'Escuchando...',
        'coach.ready': 'Listo',
        'coach.rate_my_laugh': 'Calificar mi Risa',
        'coach.stop_rate': 'Detener y Calificar',
        'coach.energy': 'Energía',
        'coach.play_again': 'Jugar de Nuevo',
        'coach.offline_voice': 'Usando Voz Offline (Problema de Conexión)',
        'coach.laughter_log': 'Registro de Risa',
        'coach.clear': 'Borrar',
        'coach.clear_confirm': '¿Seguro que quieres borrar tu registro?',
        'coach.thanks_feedback': '¡Gracias por tus comentarios!',
        'coach.session_completed': 'Sesión Completada',
        'coach.laughter_analyzed': 'Risa Analizada',
        'coach.mic_permission': '¡Permite el acceso al micrófono para usar el Entrenador!',
        'coach.analyze_error': "No se pudo analizar la risa. ¡Inténtalo de nuevo!",
        'coach.session_error': 'No se pudo iniciar la sesión.',
        'coach.connection_lost': 'Conexión perdida.',
        'coach.live_unavailable': 'Falta clave API. Sesión en vivo no disponible.',
    },
    ar: {
        'home.welcome': 'أشعل فرحك الداخلي',
        'home.subtitle': 'عزز المناعة وخفف التوتر بتوجيه من خبيرة يوغا الضحك सुमन सुनेजा.',
        'home.test_laugh': 'اختبر ضحكتك',
        'nav.home': 'الرئيسية',
        'nav.videos': 'فيديو',
        'nav.games': 'ألعاب',
        'nav.coach': 'مدرب',
        'nav.ask_ai': 'اسأل سومان',
        'profile.title': 'ملفك الشخصي',
        'profile.subtitle': 'خصص هويتك السعيدة',
        'settings.title': 'إعدادات',
        'settings.dark_mode': 'الوضع الليلي',
        'settings.language': 'اللغة',
        'settings.font_size': 'حجم الخط',
        'streak': 'أيام متتالية',
        'points': 'نقاط',
        'level': 'مستوى',
        'today': 'اليوم',
        'save_changes': 'حفظ التغييرات',
        'sign_out': 'تسجيل خروج',
        'daily_session': 'يوغا الضحك اليومية',
        'join_session': 'انضم للجلسة',
        'every_day': 'كل يوم',
        'traditional_yoga': 'يوغا تقليدية وضحك',
        'join_yoga': 'انضم لصف اليوغا',
        'mon_fri': 'اثنين - جمعة',
        'fun_games': 'ألعاب مرحة',
        'book_session': 'احجز جلسة',
        'contact': 'اتصل بنا',

        // Contact
        'contact.header_title': "لنصنع السحر!",
        'contact.header_subtitle': "حجز جلسة هو الخطوة الأولى لحياة أكثر سعادة.",
        'contact.whatsapp_btn': "واتساب",
        'contact.instant_reply': "رد فوري",
        'contact.email_btn': "أرسل بريد إلكتروني",
        'contact.for_enquiries': "للاستفسارات",
        'contact.offerings_title': "ماذا نقدم",
        'contact.offering_1_title': "1-على-1",
        'contact.offering_1_desc': "تدريب شخصي",
        'contact.offering_2_title': "شركات",
        'contact.offering_2_desc': "تخفيف التوتر",
        'contact.offering_3_title': "مجموعات",
        'contact.offering_3_desc': "ورش عمل",
        'contact.offering_4_title': "خلوات",
        'contact.offering_4_desc': "أيام العافية",
        'contact.youtube_btn': "شاهد على يوتيوب",
        'contact.subscribe': "اشترك",
        'contact.website_btn': "زيارة الموقع الرسمي",
        'app.developed_by': "تم تطوير التطبيق بواسطة",

        // Profile
        'profile.display_name': "الاسم المعروض",
        'profile.enter_name_placeholder': "أدخل اسمك",
        'profile.phone_number': "رقم الهاتف",
        'profile.no_number': "لا يوجد رقم مرتبط",
        'profile.streak_power': "قوة التتابع",
        'profile.streak_power_description': "حافظ على سلسلة ضحكك حية لفتح شارات حصرية ومحتوى متميز!",
        'profile.start_today': "ابدأ اليوم!",
        'profile.bonus': "مكافأة",
        'profile.personal_info': "معلومات شخصية",
        'profile.edit_button': "تعديل",
        'profile.link_button': "رابط",

        // Games
        'games.title': "مختبر ضحك الذكاء الاصطناعي",
        'games.subtitle_jokes': "مولد النكات",
        'games.subtitle_joy': "مولد الفرح",
        'games.tab_story': "قصة",
        'games.tab_jokes': "نكات",
        'games.tab_moods': "مزاج",
        'games.speaking': "يتحدث...",
        'games.writing_joke': "يكتب نكتة...",
        'games.brewing_laughter': "يخمر الضحك...",
        'games.funny_mode': "وضع مضحك",
        'games.ai_mode': "وضع الذكاء الاصطناعي",
        'games.play_real_laughter': "تشغيل ضحك حقيقي",
        'games.offline_voice': "صوت غير متصل",
        'games.input_placeholder_story': "موقف (مثلاً: فاتني المنبه)",
        'games.input_placeholder_joke': "موضوع (مثلاً: قطط، مدير، قهوة)",
        'games.input_placeholder_mood': "اختر مزاجاً لسماع ضحكات مختلفة.",
        'games.btn_joke': "قل لي نكتة واضحك!",
        'games.btn_story': "توليد قصة فرح",
        'games.stop_audio': "إيقاف الصوت",
        'games.mood_giggle': "قهقهة",
        'games.mood_belly': "ضحك من البطن",
        'games.mood_snort': "ضحك مع شخير",
        'games.mood_cackle': "ضحكة ساحرة",

        // Video Library
        'video.title': 'مكتبة الفيديو',
        'video.visit_channel': 'زيارة القناة الرسمية',
        'video.count_suffix': 'فيديو',
        'video.tab_all': 'كل الفيديوهات',
        'video.tab_favorites': 'المفضلة',
        'video.tab_offline': 'بدون نت',
        'video.search_placeholder': 'بحث عن فيديو...',
        'video.filter_all': 'الكل',
        'video.no_videos': 'لا توجد فيديوهات',
        'video.now_playing': 'يشتغل الآن',
        'video.open_app': 'فتح في التطبيق',
        'video.save_offline': 'حفظ بدون نت',
        'video.saving': 'جاري الحفظ...',
        'video.saved': 'تم الحفظ',
        'video.remove_confirm': 'إزالة من المكتبة؟',
        'video.saved_toast': 'تم حفظ الفيديو',
        'video.started_toast': 'بدأت الجلسة',
        'video.page': 'صفحة',
        'video.of': 'من',
        'video.category_events': 'أحداث',
        'video.category_corporate': 'شركات',
        'video.category_health': 'صحة',
        'video.category_exercises': 'تمارين',
        'video.category_fun': 'مرح',
        'video.category_morning': 'صباح',
        'video.category_meditation': 'تأمل',
        'video.category_stress_relief': 'تخفيف التوتر',
        'video.category_daily': 'يومي',
        'video.category_sessions': 'جلسات',
        'video.category_seniors': 'كبار السن',

        // Laughter Coach
        'coach.title': 'مدرب الضحك',
        'coach.subtitle': 'اضحك بصوت عالٍ للحصول على نقاط السعادة!',
        'coach.how_was_it': 'كيف كان؟',
        'coach.help_improve': 'ساعدنا في التحسين!',
        'coach.skip_feedback': 'تخطي',
        'coach.start_live': 'بدء جلسة مباشرة',
        'coach.interactive': 'محادثة تفاعلية',
        'coach.quick_laugh': 'ضحكة سريعة دقيقة',
        'coach.guided_boost': 'تعزيز الطاقة',
        'coach.analyzing': 'تحليل الفرح...',
        'coach.api_missing': 'مفتاح API مفقود!',
        'coach.offline_fallback': 'العودة للوضع غير المتصل',
        'coach.joy_score': 'نقاط الفرح',
        'coach.ai_listening': 'الذكاء الاصطناعي يستمع...',
        'coach.listen_laugh': 'استمع واضحك',
        'coach.listening': 'يستمع...',
        'coach.ready': 'جاهز',
        'coach.rate_my_laugh': 'قيم ضحكتي',
        'coach.stop_rate': 'توقف وقيم',
        'coach.energy': 'طاقة',
        'coach.play_again': 'العب مرة أخرى',
        'coach.offline_voice': 'صوت غير متصل (مشكلة اتصال)',
        'coach.laughter_log': 'سجل الضحك',
        'coach.clear': 'مسح',
        'coach.clear_confirm': 'هل أنت متأكد من مسح السجل؟',
        'coach.thanks_feedback': 'شكراً لملاحظاتك!',
        'coach.session_completed': 'اكتملت الجلسة',
        'coach.laughter_analyzed': 'تم تحليل الضحك',
        'coach.mic_permission': 'يرجى السماح باستخدام الميكروفون!',
        'coach.analyze_error': "تعذر تحليل الضحك. حاول مرة أخرى!",
        'coach.session_error': 'تعذر بدء الجلسة.',
        'coach.connection_lost': 'فقد الاتصال.',
        'coach.live_unavailable': 'مفتاح API مفقود.',
    },
    fr: {
        'home.welcome': 'Allumez votre joie intérieure',
        'home.subtitle': 'Boostez l\'immunité et soulagez le stress avec les conseils d\'expert de Suman Suneja.',
        'home.test_laugh': 'Testez votre rire',
        'nav.home': 'Accueil',
        'nav.videos': 'Vidéos',
        'nav.games': 'Jeux',
        'nav.coach': 'Coach',
        'nav.ask_ai': 'Demander Suman',
        'profile.title': 'Votre Profil',
        'profile.subtitle': 'Personnalisez votre identité',
        'settings.title': 'Paramètres',
        'settings.dark_mode': 'Mode Sombre',
        'settings.language': 'Langue',
        'settings.font_size': 'Taille de la police',
        'streak': 'Série',
        'points': 'Points',
        'level': 'Niveau',
        'today': 'Aujourd\'hui',
        'save_changes': 'Sauvegarder',
        'sign_out': 'Déconnexion',
        'daily_session': 'Yoga du Rire Quotidien',
        'join_session': 'Rejoindre',
        'every_day': 'Chaque Jour',
        'traditional_yoga': 'Yoga Traditionnel',
        'join_yoga': 'Rejoindre le Cours',
        'mon_fri': 'Lun - Ven',
        'fun_games': 'Jeux Amusants',
        'book_session': 'Réserver',
        'contact': 'Contact',

        // Contact
        'contact.header_title': "Faisons de la Magie !",
        'contact.header_subtitle': "Réserver une séance est la première étape vers une vie plus heureuse.",
        'contact.whatsapp_btn': "WhatsApp",
        'contact.instant_reply': "Réponse Instantanée",
        'contact.email_btn': "Envoyer Email",
        'contact.for_enquiries': "Pour Renseignements",
        'contact.offerings_title': "Ce que nous offrons",
        'contact.offering_1_title': "1-sur-1",
        'contact.offering_1_desc': "Coaching Personnel",
        'contact.offering_2_title': "Entreprise",
        'contact.offering_2_desc': "Gestion du Stress",
        'contact.offering_3_title': "Groupes",
        'contact.offering_3_desc': "Ateliers",
        'contact.offering_4_title': "Retraites",
        'contact.offering_4_desc': "Journées Bien-être",
        'contact.youtube_btn': "Voir sur YouTube",
        'contact.subscribe': "S'abonner",
        'contact.website_btn': "Visiter Site Officiel",
        'app.developed_by': "App Développée par",

        // Profile
        'profile.display_name': "Nom d'affichage",
        'profile.enter_name_placeholder': "Entrez votre nom",
        'profile.phone_number': "Numéro de téléphone",
        'profile.no_number': "Aucun numéro lié",
        'profile.streak_power': "PUISSANCE DE SÉRIE",
        'profile.streak_power_description': "Gardez votre série de rires vivante pour débloquer des badges exclusifs et du contenu premium !",
        'profile.start_today': "Commencez aujourd'hui !",
        'profile.bonus': "Bonus",
        'profile.personal_info': "Infos Personnelles",
        'profile.edit_button': "Modifier",
        'profile.link_button': "Lier",

        // Games
        'games.title': "Labo de Rire IA",
        'games.subtitle_jokes': "Générateur de Blagues",
        'games.subtitle_joy': "Générateur de Joie",
        'games.tab_story': "Histoire",
        'games.tab_jokes': "Blagues",
        'games.tab_moods': "Humeurs",
        'games.speaking': "Parle...",
        'games.writing_joke': "Écrit une blague...",
        'games.brewing_laughter': "Prépare le rire...",
        'games.funny_mode': "Mode Drôle",
        'games.ai_mode': "Mode IA",
        'games.play_real_laughter': "Jouer Rire Réel",
        'games.offline_voice': "Voix Hors Ligne",
        'games.input_placeholder_story': "Situation (ex. Réveil raté)",
        'games.input_placeholder_joke': "Sujet (ex. Chats, Patron, Café)",
        'games.input_placeholder_mood': "Choisissez une humeur.",
        'games.btn_joke': "Raconte une blague !",
        'games.btn_story': "Générer Histoire de Joie",
        'games.stop_audio': "Arrêter Audio",
        'games.mood_giggle': "Gloussement",
        'games.mood_belly': "Rire de ventre",
        'games.mood_snort': "Rire cochon",
        'games.mood_cackle': "Rire de sorcière",

        // Video Library
        'video.title': 'Vidéothèque',
        'video.visit_channel': 'Visiter Chaîne Officielle',
        'video.count_suffix': 'Vidéos',
        'video.tab_all': 'Toutes',
        'video.tab_favorites': 'Favoris',
        'video.tab_offline': 'Hors ligne',
        'video.search_placeholder': 'Rechercher vidéos...',
        'video.filter_all': 'Tous',
        'video.no_videos': 'Aucune vidéo trouvée',
        'video.now_playing': 'Lecture en cours',
        'video.open_app': 'Ouvrir dans l\'app',
        'video.save_offline': 'Sauvegarder',
        'video.saving': 'Enregistrement...',
        'video.saved': 'Enregistré',
        'video.remove_confirm': 'Supprimer de la bibliothèque hors ligne ?',
        'video.saved_toast': 'Vidéo enregistrée hors ligne',
        'video.started_toast': 'Session vidéo commencée',
        'video.page': 'Page',
        'video.of': 'de',
        'video.category_events': 'Événements',
        'video.category_corporate': 'Entreprise',
        'video.category_health': 'Santé',
        'video.category_exercises': 'Exercices',
        'video.category_fun': 'Amusement',
        'video.category_morning': 'Matin',
        'video.category_meditation': 'Méditation',
        'video.category_stress_relief': 'Gestion du Stress',
        'video.category_daily': 'Quotidien',
        'video.category_sessions': 'Séances',
        'video.category_seniors': 'Séniors',

        // Laughter Coach
        'coach.title': 'Coach de Rire',
        'coach.subtitle': 'Riez fort pour obtenir votre score de bonheur !',
        'coach.how_was_it': 'C\'était comment ?',
        'coach.help_improve': 'Aidez Suman AI à s\'améliorer !',
        'coach.skip_feedback': 'Passer',
        'coach.start_live': 'Démarrer Session Live',
        'coach.interactive': 'Conversation Interactive',
        'coach.quick_laugh': 'Rire Rapide 1-Min',
        'coach.guided_boost': 'Boost d\'Énergie Guidé',
        'coach.analyzing': 'Analyse de la Joie...',
        'coach.api_missing': 'Clé API Gemini Manquante !',
        'coach.offline_fallback': 'Passage en mode hors ligne',
        'coach.joy_score': 'Score de Joie',
        'coach.ai_listening': 'IA Écoute...',
        'coach.listen_laugh': 'Écoutez et Riez',
        'coach.listening': 'Écoute...',
        'coach.ready': 'Prêt',
        'coach.rate_my_laugh': 'Noter mon Rire',
        'coach.stop_rate': 'Arrêter et Noter',
        'coach.energy': 'Énergie',
        'coach.play_again': 'Rejouer',
        'coach.offline_voice': 'Utilisation Voix Hors Ligne (Problème Connexion)',
        'coach.laughter_log': 'Journal de Rire',
        'coach.clear': 'Effacer',
        'coach.clear_confirm': 'Voulez-vous vraiment effacer votre journal ?',
        'coach.thanks_feedback': 'Merci pour vos commentaires !',
        'coach.session_completed': 'Session Terminée',
        'coach.laughter_analyzed': 'Rire Analysé',
        'coach.mic_permission': 'Veuillez autoriser l\'accès au micro !',
        'coach.analyze_error': "Impossible d'analyser le rire. Réessayez !",
        'coach.session_error': 'Impossible de démarrer la session.',
        'coach.connection_lost': 'Connexion perdue.',
        'coach.live_unavailable': 'Clé API manquante. Session live indisponible.',
    },
    de: {
        'home.welcome': 'Entfache deine innere Freude',
        'home.subtitle': 'Stärke dein Immunsystem und baue Stress ab mit Expertenrat von Suman Suneja.',
        'home.test_laugh': 'Teste dein Lachen',
        'nav.home': 'Start',
        'nav.videos': 'Videos',
        'nav.games': 'Spiele',
        'nav.coach': 'Coach',
        'nav.ask_ai': 'Frag Suman',
        'profile.title': 'Dein Profil',
        'profile.subtitle': 'Personalisiere deine Identität',
        'settings.title': 'Einstellungen',
        'settings.dark_mode': 'Dunkelmodus',
        'settings.language': 'Sprache',
        'settings.font_size': 'Schriftgröße',
        'streak': 'Serie',
        'points': 'Punkte',
        'level': 'Level',
        'today': 'Heute',
        'save_changes': 'Speichern',
        'sign_out': 'Abmelden',
        'daily_session': 'Tägliches Lachyoga',
        'join_session': 'Beitreten',
        'every_day': 'Täglich',
        'traditional_yoga': 'Traditionelles Yoga',
        'join_yoga': 'Kurs beitreten',
        'mon_fri': 'Mo - Fr',
        'fun_games': 'Lustige Spiele',
        'book_session': 'Sitzung buchen',
        'contact': 'Kontakt',

        // Contact
        'contact.header_title': "Lass uns Magie machen!",
        'contact.header_subtitle': "Eine Sitzung zu buchen ist der erste Schritt zu einem glücklicheren Leben.",
        'contact.whatsapp_btn': "WhatsApp uns",
        'contact.instant_reply': "Sofortantwort",
        'contact.email_btn': "E-Mail senden",
        'contact.for_enquiries': "Für Anfragen",
        'contact.offerings_title': "Was wir bieten",
        'contact.offering_1_title': "1-zu-1",
        'contact.offering_1_desc': "Persönliches Coaching",
        'contact.offering_2_title': "Firmen",
        'contact.offering_2_desc': "Stressabbau",
        'contact.offering_3_title': "Gruppen",
        'contact.offering_3_desc': "Workshops",
        'contact.offering_4_title': "Retreats",
        'contact.offering_4_desc': "Wellness-Tage",
        'contact.youtube_btn': "Auf YouTube ansehen",
        'contact.subscribe': "Abonnieren",
        'contact.website_btn': "Offizielle Website",
        'app.developed_by': "App entwickelt von",

        // Profile
        'profile.display_name': "Anzeigename",
        'profile.enter_name_placeholder': "Name eingeben",
        'profile.phone_number': "Telefonnummer",
        'profile.no_number': "Keine Nummer verknüpft",
        'profile.streak_power': "SERIEN-POWER",
        'profile.streak_power_description': "Halte deine Lachserie am Leben, um exklusive Abzeichen und Premium-Inhalte freizuschalten!",
        'profile.start_today': "Starte heute!",
        'profile.bonus': "Bonus",
        'profile.personal_info': "Persönliche Infos",
        'profile.edit_button': "Bearbeiten",
        'profile.link_button': "Verknüpfen",

        // Games
        'games.title': "KI-Lachlabor",
        'games.subtitle_jokes': "Witz-Generator",
        'games.subtitle_joy': "Freude-Generator",
        'games.tab_story': "Geschichte",
        'games.tab_jokes': "Witze",
        'games.tab_moods': "Launen",
        'games.speaking': "Spricht...",
        'games.writing_joke': "Schreibt einen Witz...",
        'games.brewing_laughter': "Braut Gelächter...",
        'games.funny_mode': "Lustiger Modus",
        'games.ai_mode': "KI-Modus",
        'games.play_real_laughter': "Echtes Lachen abspielen",
        'games.offline_voice': "Offline-Stimme",
        'games.input_placeholder_story': "Situation (z.B. Wecker verpasst)",
        'games.input_placeholder_joke': "Thema (z.B. Katzen, Chef, Kaffee)",
        'games.input_placeholder_mood': "Wähle eine Stimmung.",
        'games.btn_joke': "Erzähl mir einen Witz!",
        'games.btn_story': "Freudengeschichte generieren",
        'games.stop_audio': "Audio stoppen",
        'games.mood_giggle': "Kichern",
        'games.mood_belly': "Bauchlachen",
        'games.mood_snort': "Grunzlachen",
        'games.mood_cackle': "Hexenlachen",

        // Video Library
        'video.title': 'Videothek',
        'video.visit_channel': 'Offiziellen Kanal besuchen',
        'video.count_suffix': 'Videos',
        'video.tab_all': 'Alle Videos',
        'video.tab_favorites': 'Favoriten',
        'video.tab_offline': 'Offline',
        'video.search_placeholder': 'Videos suchen...',
        'video.filter_all': 'Alle',
        'video.no_videos': 'Keine Videos gefunden',
        'video.now_playing': 'Läuft gerade',
        'video.open_app': 'In App öffnen',
        'video.save_offline': 'Offline speichern',
        'video.saving': 'Speichern...',
        'video.saved': 'Gespeichert',
        'video.remove_confirm': 'Aus Offline-Bibliothek entfernen?',
        'video.saved_toast': 'Offline-Video gespeichert',
        'video.started_toast': 'Videositzung gestartet',
        'video.page': 'Seite',
        'video.of': 'von',
        'video.category_events': 'Veranstaltungen',
        'video.category_corporate': 'Firmen',
        'video.category_health': 'Gesundheit',
        'video.category_exercises': 'Übungen',
        'video.category_fun': 'Spaß',
        'video.category_morning': 'Morgen',
        'video.category_meditation': 'Meditation',
        'video.category_stress_relief': 'Stressabbau',
        'video.category_daily': 'Täglich',
        'video.category_sessions': 'Sitzungen',
        'video.category_seniors': 'Senioren',

        // Laughter Coach
        'coach.title': 'Lach-Coach',
        'coach.subtitle': 'Lache laut, um deinen Glückswert zu erhalten!',
        'coach.how_was_it': 'Wie war es?',
        'coach.help_improve': 'Hilf Suman AI besser zu werden!',
        'coach.skip_feedback': 'Überspringen',
        'coach.start_live': 'Live-Sitzung starten',
        'coach.interactive': 'Interaktives Gespräch',
        'coach.quick_laugh': 'Schnelles 1-Min Lachen',
        'coach.guided_boost': 'Geführter Energieschub',
        'coach.analyzing': 'Analysiere Freude...',
        'coach.api_missing': 'Gemini API-Schlüssel fehlt!',
        'coach.offline_fallback': 'Wechsle in Offline-Modus',
        'coach.joy_score': 'Freude-Score',
        'coach.ai_listening': 'KI hört zu...',
        'coach.listen_laugh': 'Zuhören & Lachen',
        'coach.listening': 'Hört zu...',
        'coach.ready': 'Bereit',
        'coach.rate_my_laugh': 'Bewerte mein Lachen',
        'coach.stop_rate': 'Stopp & Bewerten',
        'coach.energy': 'Energie',
        'coach.play_again': 'Nochmal spielen',
        'coach.offline_voice': 'Offline-Stimme (Verbindungsproblem)',
        'coach.laughter_log': 'Lach-Protokoll',
        'coach.clear': 'Löschen',
        'coach.clear_confirm': 'Möchtest du dein Protokoll wirklich löschen?',
        'coach.thanks_feedback': 'Danke für dein Feedback!',
        'coach.session_completed': 'Sitzung beendet',
        'coach.laughter_analyzed': 'Lachen analysiert',
        'coach.mic_permission': 'Bitte erlaube Mikrofonzugriff!',
        'coach.analyze_error': "Konnte Lachen nicht analysieren. Versuch es nochmal!",
        'coach.session_error': 'Konnte Sitzung nicht starten.',
        'coach.connection_lost': 'Verbindung verloren.',
        'coach.live_unavailable': 'API-Schlüssel fehlt. Live-Sitzung nicht verfügbar.',
    },
    ja: {
        'home.welcome': '内なる喜びを点火しよう',
        'home.subtitle': 'Suman Sunejaの専門的な指導で免疫力を高め、ストレスを解消しましょう。',
        'home.test_laugh': '笑いをテスト',
        'nav.home': 'ホーム',
        'nav.videos': '動画',
        'nav.games': 'ゲーム',
        'nav.coach': 'コーチ',
        'nav.ask_ai': 'Sumanに聞く',
        'profile.title': 'プロフィール',
        'profile.subtitle': '喜びのIDをカスタマイズ',
        'settings.title': '設定',
        'settings.dark_mode': 'ダークモード',
        'settings.language': '言語',
        'settings.font_size': '文字サイズ',
        'streak': '連続記録',
        'points': 'ポイント',
        'level': 'レベル',
        'today': '今日',
        'save_changes': '保存',
        'sign_out': 'ログアウト',
        'daily_session': '毎日のラフターヨガ',
        'join_session': '参加する',
        'every_day': '毎日',
        'traditional_yoga': '伝統的＆ラフターヨガ',
        'join_yoga': 'クラスに参加',
        'mon_fri': '月 - 金',
        'fun_games': '楽しいゲーム',
        'book_session': 'セッション予約',
        'contact': '連絡先',

        // Contact
        'contact.header_title': "魔法を起こそう！",
        'contact.header_subtitle': "セッションの予約は、より幸せで健康的な生活への第一歩です。",
        'contact.whatsapp_btn': "WhatsApp",
        'contact.instant_reply': "即時返信",
        'contact.email_btn': "メールを送る",
        'contact.for_enquiries': "お問い合わせ",
        'contact.offerings_title': "提供サービス",
        'contact.offering_1_title': "マンツーマン",
        'contact.offering_1_desc': "パーソナルコーチング",
        'contact.offering_2_title': "企業向け",
        'contact.offering_2_desc': "ストレス解消",
        'contact.offering_3_title': "グループ",
        'contact.offering_3_desc': "ワークショップ",
        'contact.offering_4_title': "リトリート",
        'contact.offering_4_desc': "ウェルネスデー",
        'contact.youtube_btn': "YouTubeで見る",
        'contact.subscribe': "登録する",
        'contact.website_btn': "公式サイトへ",
        'app.developed_by': "アプリ開発",

        // Profile
        'profile.display_name': "表示名",
        'profile.enter_name_placeholder': "名前を入力",
        'profile.phone_number': "電話番号",
        'profile.no_number': "番号がリンクされていません",
        'profile.streak_power': "ストリークパワー",
        'profile.streak_power_description': "ストリークを維持して、限定バッジやプレミアムコンテンツを解除しよう！",
        'profile.start_today': "今日から始めよう！",
        'profile.bonus': "ボーナス",
        'profile.personal_info': "個人情報",
        'profile.edit_button': "編集",
        'profile.link_button': "リンク",

        // Games
        'games.title': "AIラフターラボ",
        'games.subtitle_jokes': "一行ジョーク生成",
        'games.subtitle_joy': "実験的喜び生成",
        'games.tab_story': "ストーリー",
        'games.tab_jokes': "ジョーク",
        'games.tab_moods': "気分",
        'games.speaking': "話しています...",
        'games.writing_joke': "ジョークを書いています...",
        'games.brewing_laughter': "笑いを醸造中...",
        'games.funny_mode': "面白いモード",
        'games.ai_mode': "AIモード",
        'games.play_real_laughter': "リアルな笑いを再生",
        'games.offline_voice': "オフライン音声",
        'games.input_placeholder_story': "状況（例：目覚まし時計の失敗）",
        'games.input_placeholder_joke': "トピック（例：猫、上司、コーヒー）",
        'games.input_placeholder_mood': "気分を選んで笑いを聞く",
        'games.btn_joke': "ジョークを言って笑わせて！",
        'games.btn_story': "喜びのストーリーを生成",
        'games.stop_audio': "音声を停止",
        'games.mood_giggle': "くすくす笑い",
        'games.mood_belly': "腹の底からの笑い",
        'games.mood_snort': "鼻を鳴らす笑い",
        'games.mood_cackle': "魔女の笑い",

        // Video Library
        'video.title': 'ビデオライブラリ',
        'video.visit_channel': '公式チャンネル',
        'video.count_suffix': '動画',
        'video.tab_all': 'すべて',
        'video.tab_favorites': 'お気に入り',
        'video.tab_offline': 'オフライン',
        'video.search_placeholder': '動画を検索...',
        'video.filter_all': 'すべて',
        'video.no_videos': '動画が見つかりません',
        'video.now_playing': '再生中',
        'video.open_app': 'アプリで開く',
        'video.save_offline': '保存',
        'video.saving': '保存中...',
        'video.saved': '保存済み',
        'video.remove_confirm': 'オフラインライブラリから削除しますか？',
        'video.saved_toast': 'オフラインに保存しました',
        'video.started_toast': 'セッション開始',
        'video.page': 'ページ',
        'video.of': '/',
        'video.category_events': 'イベント',
        'video.category_corporate': '企業向け',
        'video.category_health': '健康',
        'video.category_exercises': 'エクササイズ',
        'video.category_fun': '楽しい',
        'video.category_morning': '朝',
        'video.category_meditation': '瞑想',
        'video.category_stress_relief': 'ストレス解消',
        'video.category_daily': '毎日',
        'video.category_sessions': 'セッション',
        'video.category_seniors': 'シニア',

        // Laughter Coach
        'coach.title': 'ラフターコーチ',
        'coach.subtitle': '大声で笑ってハッピースコアをゲット！',
        'coach.how_was_it': 'どうでしたか？',
        'coach.help_improve': 'Suman AIの改善にご協力ください！',
        'coach.skip_feedback': 'スキップ',
        'coach.start_live': 'ライブセッション開始',
        'coach.interactive': '対話モード',
        'coach.quick_laugh': '1分間クイック笑い',
        'coach.guided_boost': 'エネルギーブースト',
        'coach.analyzing': '喜びを分析中...',
        'coach.api_missing': 'APIキーがありません！',
        'coach.offline_fallback': 'オフラインモード',
        'coach.joy_score': 'ジョイスコア',
        'coach.ai_listening': 'AIが聞いています...',
        'coach.listen_laugh': '聞いて笑おう',
        'coach.listening': '聞いています...',
        'coach.ready': '準備完了',
        'coach.rate_my_laugh': '私の笑いを評価',
        'coach.stop_rate': '停止＆評価',
        'coach.energy': 'エネルギー',
        'coach.play_again': '再プレイ',
        'coach.offline_voice': 'オフライン音声を使用中（接続の問題）',
        'coach.laughter_log': '笑いの記録',
        'coach.clear': '消去',
        'coach.clear_confirm': '記録を消去しますか？',
        'coach.thanks_feedback': 'フィードバックありがとうございます！',
        'coach.session_completed': 'セッション完了',
        'coach.laughter_analyzed': '笑いを分析しました',
        'coach.mic_permission': 'マイクの使用を許可してください！',
        'coach.analyze_error': "分析できませんでした。再試行してください。",
        'coach.session_error': 'セッションを開始できません。',
        'coach.connection_lost': '接続が切れました。',
        'coach.live_unavailable': 'APIキーがありません。',
    }
};

export interface ThemeColors {
    HERO: string;
    HERO_BUTTON: string;
    BUTTON: string;
    BUTTON_SECONDARY: string;
    GAMES: string;
    GAMES_ICON_BG: string;
    BOOK: string;
    BOOK_ICON_BG: string;
    TEXT_PRIMARY: string;
    ICON_BG: string;
    ICON_COLOR: string;
    STAT_BG_1: string;
    STAT_ICON_BG_1: string;
    STAT_BG_2: string;
    STAT_ICON_BG_2: string;
    LIVE_CARD_BG: string;
    LIVE_BTN: string;
    // Header
    HEADER_BG: string;
    HEADER_TEXT: string;
    HEADER_BORDER: string;
    SUBSCRIBE_BTN: string;
    // Music
    MUSIC_BTN: string;
    MUSIC_BTN_ACTIVE: string;
    MUSIC_ICON: string;
    // Mic
    MIC_BTN: string;
    MIC_RIPPLE: string;
    // Video Library
    VIDEO_BG: string;
    INPUT_RING: string;
    LOADING_SPINNER: string;
    TEXT_ACCENT: string;
    VIDEO_RING_1: string;
    VIDEO_RING_2: string;
    VIDEO_BORDER: string;
}

export const THEMES: Record<ColorTheme, ThemeColors> = {
    pastel: {
        HERO: "bg-[#A9A9C6]",
        HERO_BUTTON: "bg-white text-[#A9A9C6] shadow-sm hover:bg-gray-50 border-none",
        BUTTON: "bg-[#A8C8C0] text-white shadow-sm hover:brightness-105 border-none",
        BUTTON_SECONDARY: "bg-[#C0B8D0] text-white shadow-sm hover:brightness-105 border-none",
        GAMES: "bg-[#EFEFF5] text-[#5B5166] border-none",
        GAMES_ICON_BG: "bg-[#B8B8D0] text-white p-3 rounded-full mb-1",
        BOOK: "bg-[#EFEFF5] text-[#5B5166] border-none",
        BOOK_ICON_BG: "bg-[#A0B0B0] text-white p-3 rounded-full mb-1",
        TEXT_PRIMARY: "text-[#5B5166]",
        ICON_BG: "bg-[#E8DFF5]",
        ICON_COLOR: "text-[#9B86BD]",
        STAT_BG_1: "bg-[#FFF0E0] border border-orange-100",
        STAT_ICON_BG_1: "bg-white text-orange-400",
        STAT_BG_2: "bg-[#F0F0FF] border border-purple-100",
        STAT_ICON_BG_2: "bg-white text-purple-400",
        LIVE_CARD_BG: "bg-white border-2 border-purple-100",
        LIVE_BTN: "bg-[#A8C8C0] text-white hover:brightness-105 shadow-md",
        // Header
        HEADER_BG: "bg-[#EFEFF5]",
        HEADER_TEXT: "text-[#5B5166]",
        HEADER_BORDER: "border-[#B8B8D0]/20",
        SUBSCRIBE_BTN: "bg-[#C0B8D0] hover:bg-[#B0A8C0]",
        // Music
        MUSIC_BTN: "bg-white border-[#EDE8F8] text-[#C3B8D5] hover:border-[#A8C8C0] hover:text-[#A8C8C0]",
        MUSIC_BTN_ACTIVE: "bg-[#A8C8C0] border-white text-white",
        MUSIC_ICON: "text-[#A8C8C0]",
        // Mic
        MIC_BTN: "bg-[#C0B8D0] text-white hover:scale-110",
        MIC_RIPPLE: "bg-[#C0B8D0]/30",
        // Video Library
        VIDEO_BG: "bg-[#FEF4E6]",
        INPUT_RING: "focus:ring-[#ABCEC9]",
        LOADING_SPINNER: "border-[#ABCEC9]",
        TEXT_ACCENT: "text-[#ABCEC9]",
        VIDEO_RING_1: "bg-[#C0B8D0]/20",
        VIDEO_RING_2: "bg-[#C0B8D0]/40",
        VIDEO_BORDER: "border-[#C0B8D0]/50"
    },
    red_brick: {
        HERO: "bg-[linear-gradient(110deg,#592E2E_0%,#8C4A4A_50%,#592E2E_100%)]",
        HERO_BUTTON: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] shadow-lg transition-colors",
        BUTTON: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] shadow-md transition-colors",
        BUTTON_SECONDARY: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] shadow-md transition-colors",
        GAMES: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] transition-colors",
        GAMES_ICON_BG: "text-[#8B3A3A] group-hover:text-[#FFF8F0] mb-1",
        BOOK: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] transition-colors",
        BOOK_ICON_BG: "text-[#8B3A3A] group-hover:text-[#FFF8F0] mb-1",
        TEXT_PRIMARY: "text-[#934139]",
        ICON_BG: "bg-pink-100",
        ICON_COLOR: "text-pink-500",
        STAT_BG_1: "bg-[#FFF8F0] border border-orange-100",
        STAT_ICON_BG_1: "bg-white text-orange-500",
        STAT_BG_2: "bg-[#F8F0FF] border border-purple-100",
        STAT_ICON_BG_2: "bg-white text-purple-500",
        LIVE_CARD_BG: "bg-white/70 backdrop-blur-xl border-2 border-purple-300/50",
        LIVE_BTN: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] shadow-lg transition-colors",
        // Header
        HEADER_BG: "bg-[#FEF4E6]",
        HEADER_TEXT: "text-[#783766]",
        HEADER_BORDER: "border-[#783766]/10",
        SUBSCRIBE_BTN: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] transition-colors",
        // Music
        MUSIC_BTN: "bg-white border-[#EDE8F8] text-[#C3B8D5] hover:border-[#8B3A3A] hover:text-[#8B3A3A]",
        MUSIC_BTN_ACTIVE: "bg-[#8B3A3A] border-white text-white",
        MUSIC_ICON: "text-[#8B3A3A]",
        // Mic
        MIC_BTN: "bg-[#FFF8F0] text-[#8B3A3A] border-2 border-[#8B3A3A] hover:bg-[#8B3A3A] hover:text-[#FFF8F0] hover:border-[#FFF8F0] transition-colors hover:scale-110",
        MIC_RIPPLE: "bg-[#8B3A3A]/30",
        // Video Library
        VIDEO_BG: "bg-[#FEF4E6]",
        INPUT_RING: "focus:ring-[#8B3A3A]",
        LOADING_SPINNER: "border-[#8B3A3A]",
        TEXT_ACCENT: "text-[#8B3A3A]",
        VIDEO_RING_1: "bg-[#8B3A3A]/20",
        VIDEO_RING_2: "bg-[#8B3A3A]/40",
        VIDEO_BORDER: "border-[#8B3A3A]/50"
    }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('app_theme') as Theme) || 'light');
    const [colorTheme, setColorTheme] = useState<ColorTheme>(() => (localStorage.getItem('app_color_theme') as ColorTheme) || 'red_brick');
    const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('app_lang') as Language) || 'en');
    const [fontSize, setFontSize] = useState<FontSize>(() => (localStorage.getItem('app_fontsize') as FontSize) || 'normal');
    const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr');

    const currentTheme = THEMES[colorTheme] || THEMES.red_brick;

    useEffect(() => {
        localStorage.setItem('app_theme', theme);
        if (theme === 'dark') {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    }, [theme]);

    useEffect(() => {
        localStorage.setItem('app_color_theme', colorTheme);
    }, [colorTheme]);

    useEffect(() => {
        localStorage.setItem('app_lang', language);
        document.documentElement.lang = language;
        const direction = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.dir = direction;
        setDir(direction);
    }, [language]);

    useEffect(() => {
        localStorage.setItem('app_fontsize', fontSize);
        const sizeMap = {
            small: '14px',
            normal: '16px',
            large: '19px',
            xl: '22px'
        };
        document.documentElement.style.fontSize = sizeMap[fontSize];
    }, [fontSize]);

    const toggleTheme = () => setTheme(prev => prev === 'light' ? 'dark' : 'light');

    const t = (key: string) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <SettingsContext.Provider value={{ theme, toggleTheme, colorTheme, setColorTheme, currentTheme, language, setLanguage, fontSize, setFontSize, t, dir }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (!context) throw new Error('useSettings must be used within SettingsProvider');
    return context;
};