import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'ar' | 'fr' | 'de' | 'ja';
export type Theme = 'light' | 'dark';
export type ColorTheme = 'red_brick' | 'pastel';
export type FontSize = 'small' | 'normal' | 'large' | 'xl';

export const SUPPORTED_LANGUAGES: { code: Language; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'à¤¹à¤¿à¤‚à¤¦à¥€' },
  { code: 'es', label: 'EspaÃ±ol' },
  { code: 'ar', label: 'Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©' },
  { code: 'fr', label: 'FranÃ§ais' },
  { code: 'de', label: 'Deutsch' },
  { code: 'ja', label: 'æ—¥æœ¬èªž' },
];

interface SettingsContextType {
  theme: Theme;
  toggleTheme: () => void;
  colorTheme: ColorTheme;
  setColorTheme: (theme: ColorTheme) => void;
  currentTheme: ThemeColors;
  language: Language;
  setLanguage: (lang: Language) => void;
  fontSize: FontSize;
  setFontSize: (size: FontSize) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'home.welcome': 'Ignite Your Inner Joy',
    'home.subtitle': 'Boost immunity & relieve stress with expert guidance from Suman Suneja.',
    'home.test_laugh': 'Test Your Laugh',
    'nav.home': 'Home',
    'nav.videos': 'Videos',
    'nav.games': 'Games',
    'nav.coach': 'Coach',
    'nav.ask_ai': 'Ask Suman',
    'profile.title': 'Your Profile',
    'profile.subtitle': 'Customize your joy identity',
    'settings.title': 'Settings',
    'settings.dark_mode': 'Dark Mode',
    'settings.language': 'Language',
    'settings.font_size': 'Font Size',
    'streak': 'Day Streak',
    'points': 'Points',
    'level': 'Level',
    'today': 'Today',
    'save_changes': 'Save Changes',
    'sign_out': 'Sign Out',
    'daily_session': 'Daily Laughter Yoga',
    'join_session': 'Join Daily Session',
    'every_day': 'Every Day',
    'traditional_yoga': 'Traditional & Laughter Yoga',
    'join_yoga': 'Join Yoga Class',
    'mon_fri': 'Mon - Fri',
    'fun_games': 'Fun Games',
    'book_session': 'Book Session',
    'contact': 'Contact',

    // Contact
    'contact.header_title': "Let's Make Magic Happen!",
    'contact.header_subtitle': "Booking a session is the first step to a happier, healthier life.",
    'contact.whatsapp_btn': "WhatsApp Us",
    'contact.instant_reply': "Instant Reply",
    'contact.email_btn': "Send Email",
    'contact.for_enquiries': "For Enquiries",
    'contact.offerings_title': "What we offer",
    'contact.offering_1_title': "1-on-1",
    'contact.offering_1_desc': "Personal Coaching",
    'contact.offering_2_title': "Corporate",
    'contact.offering_2_desc': "Stress Relief",
    'contact.offering_3_title': "Groups",
    'contact.offering_3_desc': "Workshops",
    'contact.offering_4_title': "Retreats",
    'contact.offering_4_desc': "Wellness Days",
    'contact.youtube_btn': "Watch on YouTube",
    'contact.subscribe': "Subscribe",
    'contact.website_btn': "Visit Official Website",
    'app.developed_by': "App Developed by",

    // Profile
    'profile.display_name': "Display Name",
    'profile.enter_name_placeholder': "Enter your name",
    'profile.phone_number': "Phone Number",
    'profile.no_number': "No number linked",
    'profile.streak_power': "STREAK POWER",
    'profile.streak_power_description': "Keep your laughter streak alive to unlock exclusive badges and premium content!",
    'profile.start_today': "Start today!",
    'profile.bonus': "Bonus",
    'profile.personal_info': "Personal Info",
    'profile.edit_button': "Edit",
    'profile.link_button': "Link",

    // Games
    'games.title': "AI Laughter Lab",
    'games.subtitle_jokes': "One-Liner Joke Generator",
    'games.subtitle_joy': "Experimental Joy Generator",
    'games.tab_story': "Story",
    'games.tab_jokes': "Jokes",
    'games.tab_moods': "Moods",
    'games.speaking': "Speaking...",
    'games.writing_joke': "Writing a zinger...",
    'games.brewing_laughter': "Brewing Laughter...",
    'games.funny_mode': "Funny Mode",
    'games.ai_mode': "AI Mode",
    'games.play_real_laughter': "Play Real Laughter",
    'games.offline_voice': "Offline Voice",
    'games.input_placeholder_story': "Situation (e.g. Missed Alarm)",
    'games.input_placeholder_joke': "Topic (e.g. Cats, Boss, Coffee)",
    'games.input_placeholder_mood': "Select a mood to hear different laughter styles.",
    'games.btn_joke': "Tell Me a Joke & Laugh!",
    'games.btn_story': "Generate Joy Story",
    'games.stop_audio': "Stop Audio",
    'games.mood_giggle': "Giggle Fit",
    'games.mood_belly': "Belly Laugh",
    'games.mood_snort': "Snort Laugh",
    'games.mood_cackle': "Witchy Cackle",

    // Video Library
    'video.title': 'Video Library',
    'video.visit_channel': 'Visit Official Channel',
    'video.count_suffix': 'Videos',
    'video.tab_all': 'All Videos',
    'video.tab_favorites': 'Favorites',
    'video.tab_offline': 'Offline',
    'video.search_placeholder': 'Search videos...',
    'video.filter_all': 'All',
    'video.no_videos': 'No videos found',
    'video.now_playing': 'Now Playing',
    'video.open_app': 'Open in App',
    'video.save_offline': 'Save Offline',
    'video.saving': 'Saving...',
    'video.saved': 'Saved',
    'video.remove_confirm': 'Remove from offline library?',
    'video.saved_toast': 'Offline Video Saved',
    'video.started_toast': 'Video Session Started',
    'video.page': 'Page',
    'video.of': 'of',
    'video.category_events': 'Events',
    'video.category_corporate': 'Corporate',
    'video.category_health': 'Health',
    'video.category_exercises': 'Exercises',
    'video.category_fun': 'Fun',
    'video.category_morning': 'Morning',
    'video.category_meditation': 'Meditation',
    'video.category_stress_relief': 'Stress Relief',
    'video.category_daily': 'Daily',
    'video.category_sessions': 'Sessions',
    'video.category_seniors': 'Seniors',

    // Laughter Coach
    'coach.title': 'Laughter Coach',
    'coach.subtitle': 'Laugh loudly to get your happiness score!',
    'coach.how_was_it': 'How was it?',
    'coach.help_improve': 'Help Suman AI improve!',
    'coach.skip_feedback': 'Skip Feedback',
    'coach.start_live': 'Start Live Session',
    'coach.interactive': 'Interactive Conversation',
    'coach.quick_laugh': 'Quick 1-Min Laugh',
    'coach.guided_boost': 'Guided Energy Boost',
    'coach.analyzing': 'Analyzing Joy...',
    'coach.api_missing': 'Gemini API Key Missing!',
    'coach.offline_fallback': 'Falling back to offline mode',
    'coach.joy_score': 'Joy Score',
    'coach.ai_listening': 'AI Listening...',
    'coach.listen_laugh': 'Listen & Laugh',
    'coach.listening': 'Listening...',
    'coach.ready': 'Ready',
    'coach.rate_my_laugh': 'Rate My Laugh',
    'coach.stop_rate': 'Stop & Rate',
    'coach.energy': 'Energy',
    'coach.play_again': 'Play Again',
    'coach.offline_voice': 'Using Offline Voice (Connection Issue)',
    'coach.laughter_log': 'Laughter Log',
    'coach.clear': 'Clear',
    'coach.clear_confirm': 'Are you sure you want to clear your laughter log?',
    'coach.thanks_feedback': 'Thanks for Feedback!',
    'coach.session_completed': 'Session Completed',
    'coach.laughter_analyzed': 'Laughter Analyzed',
    'coach.mic_permission': 'Please allow microphone access to use the Coach!',
    'coach.analyze_error': "Couldn't analyze the laughter. Try again!",
    'coach.session_error': 'Unable to start session.',
    'coach.connection_lost': 'Connection lost.',
    'coach.live_unavailable': 'API Key missing. Live session unavailable.',
  },
  hi: {
    'home.welcome': 'à¤…à¤ªà¤¨à¥€ à¤†à¤‚à¤¤à¤°à¤¿à¤• à¤–à¥à¤¶à¥€ à¤•à¥‹ à¤œà¤—à¤¾à¤à¤‚',
    'home.subtitle': 'à¤¸à¥à¤®à¤¨ à¤¸à¥à¤¨à¥‡à¤œà¤¾ à¤•à¥‡ à¤®à¤¾à¤°à¥à¤—à¤¦à¤°à¥à¤¶à¤¨ à¤•à¥‡ à¤¸à¤¾à¤¥ à¤ªà¥à¤°à¤¤à¤¿à¤°à¤•à¥à¤·à¤¾ à¤¬à¤¢à¤¼à¤¾à¤à¤‚ à¤”à¤° à¤¤à¤¨à¤¾à¤µ à¤¦à¥‚à¤° à¤•à¤°à¥‡à¤‚à¥¤',
    'home.test_laugh': 'à¤¹à¤‚à¤¸à¥€ à¤•à¥€ à¤œà¤¾à¤‚à¤š à¤•à¤°à¥‡à¤‚',
    'nav.home': 'à¤¹à¥‹à¤®',
    'nav.videos': 'à¤µà¥€à¤¡à¤¿à¤¯à¥‹',
    'nav.games': 'à¤–à¥‡à¤²',
    'nav.coach': 'à¤•à¥‹à¤š',
    'nav.ask_ai': 'à¤¸à¥à¤®à¤¨ à¤¸à¥‡ à¤ªà¥‚à¤›à¥‡à¤‚',
    'profile.title': 'à¤†à¤ªà¤•à¥€ à¤ªà¥à¤°à¥‹à¤«à¤¾à¤‡à¤²',
    'profile.subtitle': 'à¤…à¤ªà¤¨à¥€ à¤ªà¤¹à¤šà¤¾à¤¨ à¤•à¥‹ à¤…à¤¨à¥à¤•à¥‚à¤²à¤¿à¤¤ à¤•à¤°à¥‡à¤‚',
    'settings.title': 'à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸',
    'settings.dark_mode': 'à¤¡à¤¾à¤°à¥à¤• à¤®à¥‹à¤¡',
    'settings.language': 'à¤­à¤¾à¤·à¤¾',
    'settings.font_size': 'à¤«à¤¼à¥‰à¤¨à¥à¤Ÿ à¤†à¤•à¤¾à¤°',
    'streak': 'à¤¸à¥à¤Ÿà¥à¤°à¥€à¤•',
    'points': 'à¤…à¤‚à¤•',
    'level': 'à¤¸à¥à¤¤à¤°',
    'today': 'à¤†à¤œ',
    'save_changes': 'à¤¸à¤¹à¥‡à¤œà¥‡à¤‚',
    'sign_out': 'à¤¸à¤¾à¤‡à¤¨ à¤†à¤‰à¤Ÿ',
    'daily_session': 'à¤¦à¥ˆà¤¨à¤¿à¤• à¤¹à¤¾à¤¸à¥à¤¯ à¤¯à¥‹à¤—',
    'join_session': 'à¤¶à¤¾à¤®à¤¿à¤² à¤¹à¥‹à¤‚',
    'every_day': 'à¤¹à¤° à¤¦à¤¿à¤¨',
    'traditional_yoga': 'à¤ªà¤¾à¤°à¤‚à¤ªà¤°à¤¿à¤• à¤”à¤° à¤¹à¤¾à¤¸à¥à¤¯ à¤¯à¥‹à¤—',
    'join_yoga': 'à¤¯à¥‹à¤— à¤•à¤•à¥à¤·à¤¾',
    'mon_fri': 'à¤¸à¥‹à¤® - à¤¶à¥à¤•à¥à¤°',
    'fun_games': 'à¤®à¤œà¥‡à¤¦à¤¾à¤° à¤–à¥‡à¤²',
    'book_session': 'à¤¸à¤¤à¥à¤° à¤¬à¥à¤• à¤•à¤°à¥‡à¤‚',
    'contact': 'à¤¸à¤‚à¤ªà¤°à¥à¤•',

    // Contact
    'contact.header_title': "à¤šà¤²à¥‹ à¤œà¤¾à¤¦à¥‚ à¤•à¤°à¤¤à¥‡ à¤¹à¥ˆà¤‚!",
    'contact.header_subtitle': "à¤à¤• à¤¸à¤¤à¥à¤° à¤¬à¥à¤• à¤•à¤°à¤¨à¤¾ à¤à¤• à¤–à¥à¤¶à¤¹à¤¾à¤², à¤¸à¥à¤µà¤¸à¥à¤¥ à¤œà¥€à¤µà¤¨ à¤•à¥€ à¤“à¤° à¤ªà¤¹à¤²à¤¾ à¤•à¤¦à¤® à¤¹à¥ˆà¥¤",
    'contact.whatsapp_btn': "à¤µà¥à¤¹à¤¾à¤Ÿà¥à¤¸à¤à¤ª à¤•à¤°à¥‡à¤‚",
    'contact.instant_reply': "à¤¤à¥à¤µà¤°à¤¿à¤¤ à¤‰à¤¤à¥à¤¤à¤°",
    'contact.email_btn': "à¤ˆà¤®à¥‡à¤² à¤­à¥‡à¤œà¥‡à¤‚",
    'contact.for_enquiries': "à¤ªà¥‚à¤›à¤¤à¤¾à¤› à¤•à¥‡ à¤²à¤¿à¤",
    'contact.offerings_title': "à¤¹à¤® à¤•à¥à¤¯à¤¾ à¤ªà¥à¤°à¤¦à¤¾à¤¨ à¤•à¤°à¤¤à¥‡ à¤¹à¥ˆà¤‚",
    'contact.offering_1_title': "1-à¤ªà¤°-1",
    'contact.offering_1_desc': "à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤•à¥‹à¤šà¤¿à¤‚à¤—",
    'contact.offering_2_title': "à¤•à¥‰à¤°à¥à¤ªà¥‹à¤°à¥‡à¤Ÿ",
    'contact.offering_2_desc': "à¤¤à¤¨à¤¾à¤µ à¤¸à¥‡ à¤°à¤¾à¤¹à¤¤",
    'contact.offering_3_title': "à¤¸à¤®à¥‚à¤¹",
    'contact.offering_3_desc': "à¤•à¤¾à¤°à¥à¤¯à¤¶à¤¾à¤²à¤¾à¤à¤‚",
    'contact.offering_4_title': "à¤°à¤¿à¤Ÿà¥à¤°à¥€à¤Ÿ",
    'contact.offering_4_desc': "à¤µà¥‡à¤²à¤¨à¥‡à¤¸ à¤¡à¥‡à¤œà¤¼",
    'contact.youtube_btn': "YouTube à¤ªà¤° à¤¦à¥‡à¤–à¥‡à¤‚",
    'contact.subscribe': "à¤¸à¤¦à¤¸à¥à¤¯à¤¤à¤¾ à¤²à¥‡à¤‚",
    'contact.website_btn': "à¤†à¤§à¤¿à¤•à¤¾à¤°à¤¿à¤• à¤µà¥‡à¤¬à¤¸à¤¾à¤‡à¤Ÿ à¤ªà¤° à¤œà¤¾à¤à¤‚",
    'app.developed_by': "à¤à¤ª à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤µà¤¿à¤•à¤¸à¤¿à¤¤",

    // Profile
    'profile.display_name': "à¤ªà¥à¤°à¤¦à¤°à¥à¤¶à¤¨ à¤¨à¤¾à¤®",
    'profile.enter_name_placeholder': "à¤…à¤ªà¤¨à¤¾ à¤¨à¤¾à¤® à¤¦à¤°à¥à¤œ à¤•à¤°à¥‡à¤‚",
    'profile.phone_number': "à¤«à¤¼à¥‹à¤¨ à¤¨à¤‚à¤¬à¤°",
    'profile.no_number': "à¤•à¥‹à¤ˆ à¤¨à¤‚à¤¬à¤° à¤²à¤¿à¤‚à¤• à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆ",
    'profile.streak_power': "à¤¸à¥à¤Ÿà¥à¤°à¥€à¤• à¤ªà¤¾à¤µà¤°",
    'profile.streak_power_description': "à¤µà¤¿à¤¶à¥‡à¤· à¤¬à¥ˆà¤œ à¤”à¤° à¤ªà¥à¤°à¥€à¤®à¤¿à¤¯à¤® à¤¸à¤¾à¤®à¤—à¥à¤°à¥€ à¤…à¤¨à¤²à¥‰à¤• à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤…à¤ªà¤¨à¥€ à¤¹à¤‚à¤¸à¥€ à¤•à¥€ à¤²à¤•à¥€à¤° à¤•à¥‹ à¤œà¥€à¤µà¤¿à¤¤ à¤°à¤–à¥‡à¤‚!",
    'profile.start_today': "à¤†à¤œ à¤¹à¥€ à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚!",
    'profile.bonus': "à¤¬à¥‹à¤¨à¤¸",
    'profile.personal_info': "à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤œà¤¾à¤¨à¤•à¤¾à¤°à¥€",
    'profile.edit_button': "à¤¸à¤‚à¤ªà¤¾à¤¦à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
    'profile.link_button': "à¤²à¤¿à¤‚à¤•",

    // Games
    'games.title': "à¤à¤†à¤ˆ à¤²à¤¾à¤«à¥à¤Ÿà¤° à¤²à¥ˆà¤¬",
    'games.subtitle_jokes': "à¤µà¤¨-à¤²à¤¾à¤‡à¤¨à¤° à¤œà¥‹à¤• à¤œà¥‡à¤¨à¤°à¥‡à¤Ÿà¤°",
    'games.subtitle_joy': "à¤ªà¥à¤°à¤¾à¤¯à¥‹à¤—à¤¿à¤• à¤œà¥‰à¤¯ à¤œà¥‡à¤¨à¤°à¥‡à¤Ÿà¤°",
    'games.tab_story': "à¤•à¤¹à¤¾à¤¨à¥€",
    'games.tab_jokes': "à¤šà¥à¤Ÿà¤•à¥à¤²à¥‡",
    'games.tab_moods': "à¤®à¥‚à¤¡",
    'games.speaking': "à¤¬à¥‹à¤² à¤°à¤¹à¤¾ à¤¹à¥‚à¤...",
    'games.writing_joke': "à¤à¤• à¤šà¥à¤Ÿà¤•à¥à¤²à¤¾ à¤²à¤¿à¤– à¤°à¤¹à¤¾ à¤¹à¥‚à¤...",
    'games.brewing_laughter': "à¤¹à¤‚à¤¸à¥€ à¤¬à¤¨à¤¾ à¤°à¤¹à¤¾ à¤¹à¥‚à¤...",
    'games.funny_mode': "à¤®à¤œà¥‡à¤¦à¤¾à¤° à¤®à¥‹à¤¡",
    'games.ai_mode': "à¤à¤†à¤ˆ à¤®à¥‹à¤¡",
    'games.play_real_laughter': "à¤…à¤¸à¤²à¥€ à¤¹à¤‚à¤¸à¥€ à¤šà¤²à¤¾à¤à¤‚",
    'games.offline_voice': "à¤‘à¤«à¤¼à¤²à¤¾à¤‡à¤¨ à¤†à¤µà¤¾à¤œà¤¼",
    'games.input_placeholder_story': "à¤¸à¥à¤¥à¤¿à¤¤à¤¿ (à¤œà¥ˆà¤¸à¥‡ à¤…à¤²à¤¾à¤°à¥à¤® à¤›à¥‚à¤Ÿ à¤—à¤¯à¤¾)",
    'games.input_placeholder_joke': "à¤µà¤¿à¤·à¤¯ (à¤œà¥ˆà¤¸à¥‡ à¤¬à¤¿à¤²à¥à¤²à¤¿à¤¯à¤¾à¤, à¤¬à¥‰à¤¸, à¤•à¥‰à¤«à¤¼à¥€)",
    'games.input_placeholder_mood': "à¤µà¤¿à¤­à¤¿à¤¨à¥à¤¨ à¤¹à¤‚à¤¸à¥€ à¤¶à¥ˆà¤²à¤¿à¤¯à¥‹à¤‚ à¤•à¥‹ à¤¸à¥à¤¨à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤à¤• à¤®à¥‚à¤¡ à¤šà¥à¤¨à¥‡à¤‚à¥¤",
    'games.btn_joke': "à¤®à¥à¤à¥‡ à¤à¤• à¤šà¥à¤Ÿà¤•à¥à¤²à¤¾ à¤¸à¥à¤¨à¤¾à¤“ à¤”à¤° à¤¹à¤à¤¸à¥‹!",
    'games.btn_story': "à¤œà¥‰à¤¯ à¤¸à¥à¤Ÿà¥‹à¤°à¥€ à¤œà¥‡à¤¨à¤°à¥‡à¤Ÿ à¤•à¤°à¥‡à¤‚",
    'games.stop_audio': "à¤‘à¤¡à¤¿à¤¯à¥‹ à¤°à¥‹à¤•à¥‡à¤‚",
    'games.mood_giggle': "à¤–à¤¿à¤¸à¤¿à¤¯à¤¾à¤¨à¤¾",
    'games.mood_belly': "à¤ªà¥‡à¤Ÿ à¤ªà¤•à¤¡à¤¼à¤•à¤° à¤¹à¤‚à¤¸à¤¨à¤¾",
    'games.mood_snort': "à¤¨à¤¾à¤• à¤¸à¥‡ à¤¹à¤‚à¤¸à¤¨à¤¾",
    'games.mood_cackle': "à¤šà¥à¤¡à¤¼à¥ˆà¤² à¤œà¥ˆà¤¸à¥€ à¤¹à¤‚à¤¸à¥€",

    // Video Library
    'video.title': 'à¤µà¥€à¤¡à¤¿à¤¯à¥‹ à¤²à¤¾à¤‡à¤¬à¥à¤°à¥‡à¤°à¥€',
    'video.visit_channel': 'à¤†à¤§à¤¿à¤•à¤¾à¤°à¤¿à¤• à¤šà¥ˆà¤¨à¤² à¤ªà¤° à¤œà¤¾à¤à¤‚',
    'video.count_suffix': 'à¤µà¥€à¤¡à¤¿à¤¯à¥‹',
    'video.tab_all': 'à¤¸à¤­à¥€ à¤µà¥€à¤¡à¤¿à¤¯à¥‹',
    'video.tab_favorites': 'à¤ªà¤¸à¤‚à¤¦à¥€à¤¦à¤¾',
    'video.tab_offline': 'à¤‘à¤«à¤¼à¤²à¤¾à¤‡à¤¨',
    'video.search_placeholder': 'à¤µà¥€à¤¡à¤¿à¤¯à¥‹ à¤–à¥‹à¤œà¥‡à¤‚...',
    'video.filter_all': 'à¤¸à¤­à¥€',
    'video.no_videos': 'à¤•à¥‹à¤ˆ à¤µà¥€à¤¡à¤¿à¤¯à¥‹ à¤¨à¤¹à¥€à¤‚ à¤®à¤¿à¤²à¤¾',
    'video.now_playing': 'à¤…à¤¬ à¤šà¤² à¤°à¤¹à¤¾ à¤¹à¥ˆ',
    'video.open_app': 'à¤à¤ª à¤®à¥‡à¤‚ à¤–à¥‹à¤²à¥‡à¤‚',
    'video.save_offline': 'à¤‘à¤«à¤¼à¤²à¤¾à¤‡à¤¨ à¤¸à¤¹à¥‡à¤œà¥‡à¤‚',
    'video.saving': 'à¤¸à¤¹à¥‡à¤œ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    'video.saved': 'à¤¸à¤¹à¥‡à¤œà¤¾ à¤—à¤¯à¤¾',
    'video.remove_confirm': 'à¤‘à¤«à¤¼à¤²à¤¾à¤‡à¤¨ à¤²à¤¾à¤‡à¤¬à¥à¤°à¥‡à¤°à¥€ à¤¸à¥‡ à¤¨à¤¿à¤•à¤¾à¤²à¥‡à¤‚?',
    'video.saved_toast': 'à¤‘à¤«à¤¼à¤²à¤¾à¤‡à¤¨ à¤µà¥€à¤¡à¤¿à¤¯à¥‹ à¤¸à¤¹à¥‡à¤œà¤¾ à¤—à¤¯à¤¾',
    'video.started_toast': 'à¤µà¥€à¤¡à¤¿à¤¯à¥‹ à¤¸à¤¤à¥à¤° à¤¶à¥à¤°à¥‚ à¤¹à¥à¤†',
    'video.page': 'à¤ªà¥ƒà¤·à¥à¤ ',
    'video.of': 'à¤•à¤¾',
    'video.category_events': 'à¤•à¤¾à¤°à¥à¤¯à¤•à¥à¤°à¤®',
    'video.category_corporate': 'à¤•à¥‰à¤°à¥à¤ªà¥‹à¤°à¥‡à¤Ÿ',
    'video.category_health': 'à¤¸à¥à¤µà¤¾à¤¸à¥à¤¥à¥à¤¯',
    'video.category_exercises': 'à¤µà¥à¤¯à¤¾à¤¯à¤¾à¤®',
    'video.category_fun': 'à¤®à¤œà¤¼à¤¾',
    'video.category_morning': 'à¤¸à¥à¤¬à¤¹',
    'video.category_meditation': 'à¤§à¥à¤¯à¤¾à¤¨',
    'video.category_stress_relief': 'à¤¤à¤¨à¤¾à¤µ à¤¸à¥‡ à¤°à¤¾à¤¹à¤¤',
    'video.category_daily': 'à¤¦à¥ˆà¤¨à¤¿à¤•',
    'video.category_sessions': 'à¤¸à¤¤à¥à¤°',
    'video.category_seniors': 'à¤µà¤°à¤¿à¤·à¥à¤ ',

    // Laughter Coach
    'coach.title': 'à¤¹à¤¾à¤¸à¥à¤¯ à¤•à¥‹à¤š',
    'coach.subtitle': 'à¤…à¤ªà¤¨à¤¾ à¤–à¥à¤¶à¥€ à¤¸à¥à¤•à¥‹à¤° à¤ªà¥à¤°à¤¾à¤ªà¥à¤¤ à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤œà¥‹à¤° à¤¸à¥‡ à¤¹à¤‚à¤¸à¥‡à¤‚!',
    'coach.how_was_it': 'à¤¯à¤¹ à¤•à¥ˆà¤¸à¤¾ à¤¥à¤¾?',
    'coach.help_improve': 'à¤¸à¥à¤®à¤¨ à¤à¤†à¤ˆ à¤•à¥‹ à¤¬à¥‡à¤¹à¤¤à¤° à¤¬à¤¨à¤¾à¤¨à¥‡ à¤®à¥‡à¤‚ à¤®à¤¦à¤¦ à¤•à¤°à¥‡à¤‚!',
    'coach.skip_feedback': 'à¤ªà¥à¤°à¤¤à¤¿à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤›à¥‹à¤¡à¤¼à¥‡à¤‚',
    'coach.start_live': 'à¤²à¤¾à¤‡à¤µ à¤¸à¤¤à¥à¤° à¤¶à¥à¤°à¥‚ à¤•à¤°à¥‡à¤‚',
    'coach.interactive': 'à¤‡à¤‚à¤Ÿà¤°à¥ˆà¤•à¥à¤Ÿà¤¿à¤µ à¤¬à¤¾à¤¤à¤šà¥€à¤¤',
    'coach.quick_laugh': 'à¤¤à¥à¤µà¤°à¤¿à¤¤ 1-à¤®à¤¿à¤¨à¤Ÿ à¤•à¥€ à¤¹à¤‚à¤¸à¥€',
    'coach.guided_boost': 'à¤¨à¤¿à¤°à¥à¤¦à¥‡à¤¶à¤¿à¤¤ à¤Šà¤°à¥à¤œà¤¾ à¤¬à¥‚à¤¸à¥à¤Ÿ',
    'coach.analyzing': 'à¤–à¥à¤¶à¥€ à¤•à¤¾ à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤•à¤° à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    'coach.api_missing': 'à¤œà¥‡à¤®à¤¿à¤¨à¥€ à¤à¤ªà¥€à¤†à¤ˆ à¤•à¥à¤‚à¤œà¥€ à¤—à¤¾à¤¯à¤¬ à¤¹à¥ˆ!',
    'coach.offline_fallback': 'à¤‘à¤«à¤¼à¤²à¤¾à¤‡à¤¨ à¤®à¥‹à¤¡ à¤ªà¤° à¤µà¤¾à¤ªà¤¸ à¤œà¤¾ à¤°à¤¹à¤¾ à¤¹à¥ˆ',
    'coach.joy_score': 'à¤œà¥‰à¤¯ à¤¸à¥à¤•à¥‹à¤°',
    'coach.ai_listening': 'à¤à¤†à¤ˆ à¤¸à¥à¤¨ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    'coach.listen_laugh': 'à¤¸à¥à¤¨à¥‹ à¤”à¤° à¤¹à¤‚à¤¸à¥‹',
    'coach.listening': 'à¤¸à¥à¤¨ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    'coach.ready': 'à¤¤à¥ˆà¤¯à¤¾à¤°',
    'coach.rate_my_laugh': 'à¤®à¥‡à¤°à¥€ à¤¹à¤‚à¤¸à¥€ à¤•à¥‹ à¤°à¥‡à¤Ÿ à¤•à¤°à¥‡à¤‚',
    'coach.stop_rate': 'à¤°à¥‹à¤•à¥‡à¤‚ à¤”à¤° à¤°à¥‡à¤Ÿ à¤•à¤°à¥‡à¤‚',
    'coach.energy': 'à¤Šà¤°à¥à¤œà¤¾',
    'coach.play_again': 'à¤«à¤¿à¤° à¤¸à¥‡ à¤–à¥‡à¤²à¥‡à¤‚',
    'coach.offline_voice': 'à¤‘à¤«à¤¼à¤²à¤¾à¤‡à¤¨ à¤†à¤µà¤¾à¤œà¤¼ à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤° à¤°à¤¹à¤¾ à¤¹à¥ˆ (à¤•à¤¨à¥‡à¤•à¥à¤¶à¤¨ à¤¸à¤®à¤¸à¥à¤¯à¤¾)',
    'coach.laughter_log': 'à¤¹à¤‚à¤¸à¥€ à¤²à¥‰à¤—',
    'coach.clear': 'à¤¸à¤¾à¤«à¤¼ à¤•à¤°à¥‡à¤‚',
    'coach.clear_confirm': 'à¤•à¥à¤¯à¤¾ à¤†à¤ª à¤µà¤¾à¤•à¤ˆ à¤…à¤ªà¤¨à¤¾ à¤¹à¤‚à¤¸à¥€ à¤²à¥‰à¤— à¤¸à¤¾à¤«à¤¼ à¤•à¤°à¤¨à¤¾ à¤šà¤¾à¤¹à¤¤à¥‡ à¤¹à¥ˆà¤‚?',
    'coach.thanks_feedback': 'à¤ªà¥à¤°à¤¤à¤¿à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤•à¥‡ à¤²à¤¿à¤ à¤§à¤¨à¥à¤¯à¤µà¤¾à¤¦!',
    'coach.session_completed': 'à¤¸à¤¤à¥à¤° à¤ªà¥‚à¤°à¤¾ à¤¹à¥à¤†',
    'coach.laughter_analyzed': 'à¤¹à¤‚à¤¸à¥€ à¤•à¤¾ à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤•à¤¿à¤¯à¤¾ à¤—à¤¯à¤¾',
    'coach.mic_permission': 'à¤•à¥‹à¤š à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤•à¥ƒà¤ªà¤¯à¤¾ à¤®à¤¾à¤‡à¤•à¥à¤°à¥‹à¤«à¤¼à¥‹à¤¨ à¤à¤•à¥à¤¸à¥‡à¤¸ à¤•à¥€ à¤…à¤¨à¥à¤®à¤¤à¤¿ à¤¦à¥‡à¤‚!',
    'coach.analyze_error': "à¤¹à¤‚à¤¸à¥€ à¤•à¤¾ à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤¨à¤¹à¥€à¤‚ à¤•à¤° à¤¸à¤•à¤¾à¥¤ à¤ªà¥à¤¨à¤ƒ à¤ªà¥à¤°à¤¯à¤¾à¤¸ à¤•à¤°à¥‡à¤‚!",
    'coach.session_error': 'à¤¸à¤¤à¥à¤° à¤¶à¥à¤°à¥‚ à¤•à¤°à¤¨à¥‡ à¤®à¥‡à¤‚ à¤…à¤¸à¤®à¤°à¥à¤¥à¥¤',
    'coach.connection_lost': 'à¤•à¤¨à¥‡à¤•à¥à¤¶à¤¨ à¤Ÿà¥‚à¤Ÿ à¤—à¤¯à¤¾à¥¤',
    'coach.live_unavailable': 'à¤à¤ªà¥€à¤†à¤ˆ à¤•à¥à¤‚à¤œà¥€ à¤—à¤¾à¤¯à¤¬ à¤¹à¥ˆà¥¤ à¤²à¤¾à¤‡à¤µ à¤¸à¤¤à¥à¤° à¤…à¤¨à¥à¤ªà¤²à¤¬à¥à¤§ à¤¹à¥ˆà¥¤',
  },
  es: {
    'home.welcome': 'Enciende tu AlegrÃ­a',
    'home.subtitle': 'Mejora la inmunidad y alivia el estrÃ©s con Suman Suneja.',
    'home.test_laugh': 'Prueba tu Risa',
    'nav.home': 'Inicio',
    'nav.videos': 'Videos',
    'nav.games': 'Juegos',
    'nav.coach': 'Entrenador',
    'nav.ask_ai': 'Pregunta Suman',
    'profile.title': 'Tu Perfil',
    'profile.subtitle': 'Personaliza tu identidad',
    'settings.title': 'Ajustes',
    'settings.dark_mode': 'Modo Oscuro',
    'settings.language': 'Idioma',
    'settings.font_size': 'TamaÃ±o de letra',
    'streak': 'Racha',
    'points': 'Puntos',
    'level': 'Nivel',
    'today': 'Hoy',
    'save_changes': 'Guardar',
    'sign_out': 'Salir',
    'daily_session': 'Yoga de la Risa',
    'join_session': 'Unirse',
    'every_day': 'Diario',
    'traditional_yoga': 'Yoga Tradicional',
    'join_yoga': 'Unirse Clase',
    'mon_fri': 'Lun - Vie',
    'fun_games': 'Juegos',
    'book_session': 'Reservar',
    'contact': 'Contacto',

    // Contact
    'contact.header_title': "Â¡Hagamos Magia!",
    'contact.header_subtitle': "Reservar una sesiÃ³n es el primer paso hacia una vida mÃ¡s feliz.",
    'contact.whatsapp_btn': "WhatsApp",
    'contact.instant_reply': "Respuesta Inmediata",
    'contact.email_btn': "Enviar Email",
    'contact.for_enquiries': "Para Consultas",
    'contact.offerings_title': "Lo que ofrecemos",
    'contact.offering_1_title': "1-a-1",
    'contact.offering_1_desc': "Coaching Personal",
    'contact.offering_2_title': "Corporativo",
    'contact.offering_2_desc': "Alivio del EstrÃ©s",
    'contact.offering_3_title': "Grupos",
    'contact.offering_3_desc': "Talleres",
    'contact.offering_4_title': "Retiros",
    'contact.offering_4_desc': "DÃ­as de Bienestar",
    'contact.youtube_btn': "Ver en YouTube",
    'contact.subscribe': "Suscribirse",
    'contact.website_btn': "Visitar Sitio Web",
    'app.developed_by': "App Desarrollada por",

    // Profile
    'profile.display_name': "Nombre",
    'profile.enter_name_placeholder': "Ingresa tu nombre",
    'profile.phone_number': "TelÃ©fono",
    'profile.no_number': "Sin nÃºmero vinculado",
    'profile.streak_power': "PODER DE RACHA",
    'profile.streak_power_description': "Â¡MantÃ©n viva tu racha de risa para desbloquear insignias exclusivas y contenido premium!",
    'profile.start_today': "Â¡Empieza hoy!",
    'profile.bonus': "Bono",
    'profile.personal_info': "InformaciÃ³n Personal",
    'profile.edit_button': "Editar",
    'profile.link_button': "Enlazar",

    // Games
    'games.title': "Laboratorio de Risa IA",
    'games.subtitle_jokes': "Generador de Chistes",
    'games.subtitle_joy': "Generador de AlegrÃ­a",
    'games.tab_story': "Historia",
    'games.tab_jokes': "Chistes",
    'games.tab_moods': "Estados",
    'games.speaking': "Hablando...",
    'games.writing_joke': "Escribiendo broma...",
    'games.brewing_laughter': "Preparando risa...",
    'games.funny_mode': "Modo Gracioso",
    'games.ai_mode': "Modo IA",
    'games.play_real_laughter': "Reproducir Risa Real",
    'games.offline_voice': "Voz Offline",
    'games.input_placeholder_story': "SituaciÃ³n (ej. Alarma perdida)",
    'games.input_placeholder_joke': "Tema (ej. Gatos, Jefe, CafÃ©)",
    'games.input_placeholder_mood': "Elige un estado de Ã¡nimo.",
    'games.btn_joke': "Â¡CuÃ©ntame un chiste!",
    'games.btn_story': "Generar Historia de AlegrÃ­a",
    'games.stop_audio': "Detener Audio",
    'games.mood_giggle': "Risita",
    'games.mood_belly': "Carcajada",
    'games.mood_snort': "Risa con resoplido",
    'games.mood_cackle': "Risa de bruja",

    // Video Library
    'video.title': 'Biblioteca de Videos',
    'video.visit_channel': 'Visitar Canal Oficial',
    'video.count_suffix': 'Videos',
    'video.tab_all': 'Todos',
    'video.tab_favorites': 'Favoritos',
    'video.tab_offline': 'Offline',
    'video.search_placeholder': 'Buscar videos...',
    'video.filter_all': 'Todos',
    'video.no_videos': 'No se encontraron videos',
    'video.now_playing': 'Reproduciendo',
    'video.open_app': 'Abrir en App',
    'video.save_offline': 'Guardar Offline',
    'video.saving': 'Guardando...',
    'video.saved': 'Guardado',
    'video.remove_confirm': 'Â¿Eliminar de la biblioteca offline?',
    'video.saved_toast': 'Video guardado offline',
    'video.started_toast': 'SesiÃ³n de video iniciada',
    'video.page': 'PÃ¡gina',
    'video.of': 'de',
    'video.category_events': 'Eventos',
    'video.category_corporate': 'Corporativo',
    'video.category_health': 'Salud',
    'video.category_exercises': 'Ejercicios',
    'video.category_fun': 'DiversiÃ³n',
    'video.category_morning': 'MaÃ±ana',
    'video.category_meditation': 'MeditaciÃ³n',
    'video.category_stress_relief': 'Alivio del EstrÃ©s',
    'video.category_daily': 'Diario',
    'video.category_sessions': 'Sesiones',
    'video.category_seniors': 'Mayores',

    // Laughter Coach
    'coach.title': 'Entrenador de Risa',
    'coach.subtitle': 'Â¡RÃ­e fuerte para obtener tu puntuaciÃ³n de felicidad!',
    'coach.how_was_it': 'Â¿CÃ³mo estuvo?',
    'coach.help_improve': 'Â¡Ayuda a Suman AI a mejorar!',
    'coach.skip_feedback': 'Omitir',
    'coach.start_live': 'Iniciar SesiÃ³n en Vivo',
    'coach.interactive': 'ConversaciÃ³n Interactiva',
    'coach.quick_laugh': 'Risa RÃ¡pida 1-Min',
    'coach.guided_boost': 'Impulso de EnergÃ­a Guiado',
    'coach.analyzing': 'Analizando AlegrÃ­a...',
    'coach.api_missing': 'Â¡Falta Clave API Gemini!',
    'coach.offline_fallback': 'Volviendo a modo offline',
    'coach.joy_score': 'PuntuaciÃ³n de AlegrÃ­a',
    'coach.ai_listening': 'IA Escuchando...',
    'coach.listen_laugh': 'Escucha y RÃ­e',
    'coach.listening': 'Escuchando...',
    'coach.ready': 'Listo',
    'coach.rate_my_laugh': 'Calificar mi Risa',
    'coach.stop_rate': 'Detener y Calificar',
    'coach.energy': 'EnergÃ­a',
    'coach.play_again': 'Jugar de Nuevo',
    'coach.offline_voice': 'Usando Voz Offline (Problema de ConexiÃ³n)',
    'coach.laughter_log': 'Registro de Risa',
    'coach.clear': 'Borrar',
    'coach.clear_confirm': 'Â¿Seguro que quieres borrar tu registro?',
    'coach.thanks_feedback': 'Â¡Gracias por tus comentarios!',
    'coach.session_completed': 'SesiÃ³n Completada',
    'coach.laughter_analyzed': 'Risa Analizada',
    'coach.mic_permission': 'Â¡Permite el acceso al micrÃ³fono para usar el Entrenador!',
    'coach.analyze_error': "No se pudo analizar la risa. Â¡IntÃ©ntalo de nuevo!",
    'coach.session_error': 'No se pudo iniciar la sesiÃ³n.',
    'coach.connection_lost': 'ConexiÃ³n perdida.',
    'coach.live_unavailable': 'Falta clave API. SesiÃ³n en vivo no disponible.',
  },
  ar: {
    'home.welcome': 'Ø£Ø´Ø¹Ù„ ÙØ±Ø­Ùƒ Ø§Ù„Ø¯Ø§Ø®Ù„ÙŠ',
    'home.subtitle': 'Ø¹Ø²Ø² Ø§Ù„Ù…Ù†Ø§Ø¹Ø© ÙˆØ®ÙÙ Ø§Ù„ØªÙˆØªØ± Ø¨ØªÙˆØ¬ÙŠÙ‡ Ù…Ù† Ø®Ø¨ÙŠØ±Ø© ÙŠÙˆØºØ§ Ø§Ù„Ø¶Ø­Ùƒ à¤¸à¥à¤®à¤¨ Ø³ÙˆÙ†ÙŠØ¬Ø§.',
    'home.test_laugh': 'Ø§Ø®ØªØ¨Ø± Ø¶Ø­ÙƒØªÙƒ',
    'nav.home': 'Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©',
    'nav.videos': 'ÙÙŠØ¯ÙŠÙˆ',
    'nav.games': 'Ø£Ù„Ø¹Ø§Ø¨',
    'nav.coach': 'Ù…Ø¯Ø±Ø¨',
    'nav.ask_ai': 'Ø§Ø³Ø£Ù„ Ø³ÙˆÙ…Ø§Ù†',
    'profile.title': 'Ù…Ù„ÙÙƒ Ø§Ù„Ø´Ø®ØµÙŠ',
    'profile.subtitle': 'Ø®ØµØµ Ù‡ÙˆÙŠØªÙƒ Ø§Ù„Ø³Ø¹ÙŠØ¯Ø©',
    'settings.title': 'Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª',
    'settings.dark_mode': 'Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„Ù„ÙŠÙ„ÙŠ',
    'settings.language': 'Ø§Ù„Ù„ØºØ©',
    'settings.font_size': 'Ø­Ø¬Ù… Ø§Ù„Ø®Ø·',
    'streak': 'Ø£ÙŠØ§Ù… Ù…ØªØªØ§Ù„ÙŠØ©',
    'points': 'Ù†Ù‚Ø§Ø·',
    'level': 'Ù…Ø³ØªÙˆÙ‰',
    'today': 'Ø§Ù„ÙŠÙˆÙ…',
    'save_changes': 'Ø­ÙØ¸ Ø§Ù„ØªØºÙŠÙŠØ±Ø§Øª',
    'sign_out': 'ØªØ³Ø¬ÙŠÙ„ Ø®Ø±ÙˆØ¬',
    'daily_session': 'ÙŠÙˆØºØ§ Ø§Ù„Ø¶Ø­Ùƒ Ø§Ù„ÙŠÙˆÙ…ÙŠØ©',
    'join_session': 'Ø§Ù†Ø¶Ù… Ù„Ù„Ø¬Ù„Ø³Ø©',
    'every_day': 'ÙƒÙ„ ÙŠÙˆÙ…',
    'traditional_yoga': 'ÙŠÙˆØºØ§ ØªÙ‚Ù„ÙŠØ¯ÙŠØ© ÙˆØ¶Ø­Ùƒ',
    'join_yoga': 'Ø§Ù†Ø¶Ù… Ù„ØµÙ Ø§Ù„ÙŠÙˆØºØ§',
    'mon_fri': 'Ø§Ø«Ù†ÙŠÙ† - Ø¬Ù…Ø¹Ø©',
    'fun_games': 'Ø£Ù„Ø¹Ø§Ø¨ Ù…Ø±Ø­Ø©',
    'book_session': 'Ø§Ø­Ø¬Ø² Ø¬Ù„Ø³Ø©',
    'contact': 'Ø§ØªØµÙ„ Ø¨Ù†Ø§',

    // Contact
    'contact.header_title': "Ù„Ù†ØµÙ†Ø¹ Ø§Ù„Ø³Ø­Ø±!",
    'contact.header_subtitle': "Ø­Ø¬Ø² Ø¬Ù„Ø³Ø© Ù‡Ùˆ Ø§Ù„Ø®Ø·ÙˆØ© Ø§Ù„Ø£ÙˆÙ„Ù‰ Ù„Ø­ÙŠØ§Ø© Ø£ÙƒØ«Ø± Ø³Ø¹Ø§Ø¯Ø©.",
    'contact.whatsapp_btn': "ÙˆØ§ØªØ³Ø§Ø¨",
    'contact.instant_reply': "Ø±Ø¯ ÙÙˆØ±ÙŠ",
    'contact.email_btn': "Ø£Ø±Ø³Ù„ Ø¨Ø±ÙŠØ¯ Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ",
    'contact.for_enquiries': "Ù„Ù„Ø§Ø³ØªÙØ³Ø§Ø±Ø§Øª",
    'contact.offerings_title': "Ù…Ø§Ø°Ø§ Ù†Ù‚Ø¯Ù…",
    'contact.offering_1_title': "1-Ø¹Ù„Ù‰-1",
    'contact.offering_1_desc': "ØªØ¯Ø±ÙŠØ¨ Ø´Ø®ØµÙŠ",
    'contact.offering_2_title': "Ø´Ø±ÙƒØ§Øª",
    'contact.offering_2_desc': "ØªØ®ÙÙŠÙ Ø§Ù„ØªÙˆØªØ±",
    'contact.offering_3_title': "Ù…Ø¬Ù…ÙˆØ¹Ø§Øª",
    'contact.offering_3_desc': "ÙˆØ±Ø´ Ø¹Ù…Ù„",
    'contact.offering_4_title': "Ø®Ù„ÙˆØ§Øª",
    'contact.offering_4_desc': "Ø£ÙŠØ§Ù… Ø§Ù„Ø¹Ø§ÙÙŠØ©",
    'contact.youtube_btn': "Ø´Ø§Ù‡Ø¯ Ø¹Ù„Ù‰ ÙŠÙˆØªÙŠÙˆØ¨",
    'contact.subscribe': "Ø§Ø´ØªØ±Ùƒ",
    'contact.website_btn': "Ø²ÙŠØ§Ø±Ø© Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø±Ø³Ù…ÙŠ",
    'app.developed_by': "ØªÙ… ØªØ·ÙˆÙŠØ± Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ Ø¨ÙˆØ§Ø³Ø·Ø©",

    // Profile
    'profile.display_name': "Ø§Ù„Ø§Ø³Ù… Ø§Ù„Ù…Ø¹Ø±ÙˆØ¶",
    'profile.enter_name_placeholder': "Ø£Ø¯Ø®Ù„ Ø§Ø³Ù…Ùƒ",
    'profile.phone_number': "Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ",
    'profile.no_number': "Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø±Ù‚Ù… Ù…Ø±ØªØ¨Ø·",
    'profile.streak_power': "Ù‚ÙˆØ© Ø§Ù„ØªØªØ§Ø¨Ø¹",
    'profile.streak_power_description': "Ø­Ø§ÙØ¸ Ø¹Ù„Ù‰ Ø³Ù„Ø³Ù„Ø© Ø¶Ø­ÙƒÙƒ Ø­ÙŠØ© Ù„ÙØªØ­ Ø´Ø§Ø±Ø§Øª Ø­ØµØ±ÙŠØ© ÙˆÙ…Ø­ØªÙˆÙ‰ Ù…ØªÙ…ÙŠØ²!",
    'profile.start_today': "Ø§Ø¨Ø¯Ø£ Ø§Ù„ÙŠÙˆÙ…!",
    'profile.bonus': "Ù…ÙƒØ§ÙØ£Ø©",
    'profile.personal_info': "Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø´Ø®ØµÙŠØ©",
    'profile.edit_button': "ØªØ¹Ø¯ÙŠÙ„",
    'profile.link_button': "Ø±Ø§Ø¨Ø·",

    // Games
    'games.title': "Ù…Ø®ØªØ¨Ø± Ø¶Ø­Ùƒ Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ",
    'games.subtitle_jokes': "Ù…ÙˆÙ„Ø¯ Ø§Ù„Ù†ÙƒØ§Øª",
    'games.subtitle_joy': "Ù…ÙˆÙ„Ø¯ Ø§Ù„ÙØ±Ø­",
    'games.tab_story': "Ù‚ØµØ©",
    'games.tab_jokes': "Ù†ÙƒØ§Øª",
    'games.tab_moods': "Ù…Ø²Ø§Ø¬",
    'games.speaking': "ÙŠØªØ­Ø¯Ø«...",
    'games.writing_joke': "ÙŠÙƒØªØ¨ Ù†ÙƒØªØ©...",
    'games.brewing_laughter': "ÙŠØ®Ù…Ø± Ø§Ù„Ø¶Ø­Ùƒ...",
    'games.funny_mode': "ÙˆØ¶Ø¹ Ù…Ø¶Ø­Ùƒ",
    'games.ai_mode': "ÙˆØ¶Ø¹ Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ",
    'games.play_real_laughter': "ØªØ´ØºÙŠÙ„ Ø¶Ø­Ùƒ Ø­Ù‚ÙŠÙ‚ÙŠ",
    'games.offline_voice': "ØµÙˆØª ØºÙŠØ± Ù…ØªØµÙ„",
    'games.input_placeholder_story': "Ù…ÙˆÙ‚Ù (Ù…Ø«Ù„Ø§Ù‹: ÙØ§ØªÙ†ÙŠ Ø§Ù„Ù…Ù†Ø¨Ù‡)",
    'games.input_placeholder_joke': "Ù…ÙˆØ¶ÙˆØ¹ (Ù…Ø«Ù„Ø§Ù‹: Ù‚Ø·Ø·ØŒ Ù…Ø¯ÙŠØ±ØŒ Ù‚Ù‡ÙˆØ©)",
    'games.input_placeholder_mood': "Ø§Ø®ØªØ± Ù…Ø²Ø§Ø¬Ø§Ù‹ Ù„Ø³Ù…Ø§Ø¹ Ø¶Ø­ÙƒØ§Øª Ù…Ø®ØªÙ„ÙØ©.",
    'games.btn_joke': "Ù‚Ù„ Ù„ÙŠ Ù†ÙƒØªØ© ÙˆØ§Ø¶Ø­Ùƒ!",
    'games.btn_story': "ØªÙˆÙ„ÙŠØ¯ Ù‚ØµØ© ÙØ±Ø­",
    'games.stop_audio': "Ø¥ÙŠÙ‚Ø§Ù Ø§Ù„ØµÙˆØª",
    'games.mood_giggle': "Ù‚Ù‡Ù‚Ù‡Ø©",
    'games.mood_belly': "Ø¶Ø­Ùƒ Ù…Ù† Ø§Ù„Ø¨Ø·Ù†",
    'games.mood_snort': "Ø¶Ø­Ùƒ Ù…Ø¹ Ø´Ø®ÙŠØ±",
    'games.mood_cackle': "Ø¶Ø­ÙƒØ© Ø³Ø§Ø­Ø±Ø©",

    // Video Library
    'video.title': 'Ù…ÙƒØªØ¨Ø© Ø§Ù„ÙÙŠØ¯ÙŠÙˆ',
    'video.visit_channel': 'Ø²ÙŠØ§Ø±Ø© Ø§Ù„Ù‚Ù†Ø§Ø© Ø§Ù„Ø±Ø³Ù…ÙŠØ©',
    'video.count_suffix': 'ÙÙŠØ¯ÙŠÙˆ',
    'video.tab_all': 'ÙƒÙ„ Ø§Ù„ÙÙŠØ¯ÙŠÙˆÙ‡Ø§Øª',
    'video.tab_favorites': 'Ø§Ù„Ù…ÙØ¶Ù„Ø©',
    'video.tab_offline': 'Ø¨Ø¯ÙˆÙ† Ù†Øª',
    'video.search_placeholder': 'Ø¨Ø­Ø« Ø¹Ù† ÙÙŠØ¯ÙŠÙˆ...',
    'video.filter_all': 'Ø§Ù„ÙƒÙ„',
    'video.no_videos': 'Ù„Ø§ ØªÙˆØ¬Ø¯ ÙÙŠØ¯ÙŠÙˆÙ‡Ø§Øª',
    'video.now_playing': 'ÙŠØ´ØªØºÙ„ Ø§Ù„Ø¢Ù†',
    'video.open_app': 'ÙØªØ­ ÙÙŠ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚',
    'video.save_offline': 'Ø­ÙØ¸ Ø¨Ø¯ÙˆÙ† Ù†Øª',
    'video.saving': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø­ÙØ¸...',
    'video.saved': 'ØªÙ… Ø§Ù„Ø­ÙØ¸',
    'video.remove_confirm': 'Ø¥Ø²Ø§Ù„Ø© Ù…Ù† Ø§Ù„Ù…ÙƒØªØ¨Ø©ØŸ',
    'video.saved_toast': 'ØªÙ… Ø­ÙØ¸ Ø§Ù„ÙÙŠØ¯ÙŠÙˆ',
    'video.started_toast': 'Ø¨Ø¯Ø£Øª Ø§Ù„Ø¬Ù„Ø³Ø©',
    'video.page': 'ØµÙØ­Ø©',
    'video.of': 'Ù…Ù†',
    'video.category_events': 'Ø£Ø­Ø¯Ø§Ø«',
    'video.category_corporate': 'Ø´Ø±ÙƒØ§Øª',
    'video.category_health': 'ØµØ­Ø©',
    'video.category_exercises': 'ØªÙ…Ø§Ø±ÙŠÙ†',
    'video.category_fun': 'Ù…Ø±Ø­',
    'video.category_morning': 'ØµØ¨Ø§Ø­',
    'video.category_meditation': 'ØªØ£Ù…Ù„',
    'video.category_stress_relief': 'ØªØ®ÙÙŠÙ Ø§Ù„ØªÙˆØªØ±',
    'video.category_daily': 'ÙŠÙˆÙ…ÙŠ',
    'video.category_sessions': 'Ø¬Ù„Ø³Ø§Øª',
    'video.category_seniors': 'ÙƒØ¨Ø§Ø± Ø§Ù„Ø³Ù†',

    // Laughter Coach
    'coach.title': 'Ù…Ø¯Ø±Ø¨ Ø§Ù„Ø¶Ø­Ùƒ',
    'coach.subtitle': 'Ø§Ø¶Ø­Ùƒ Ø¨ØµÙˆØª Ø¹Ø§Ù„Ù Ù„Ù„Ø­ØµÙˆÙ„ Ø¹Ù„Ù‰ Ù†Ù‚Ø§Ø· Ø§Ù„Ø³Ø¹Ø§Ø¯Ø©!',
    'coach.how_was_it': 'ÙƒÙŠÙ ÙƒØ§Ù†ØŸ',
    'coach.help_improve': 'Ø³Ø§Ø¹Ø¯Ù†Ø§ ÙÙŠ Ø§Ù„ØªØ­Ø³ÙŠÙ†!',
    'coach.skip_feedback': 'ØªØ®Ø·ÙŠ',
    'coach.start_live': 'Ø¨Ø¯Ø¡ Ø¬Ù„Ø³Ø© Ù…Ø¨Ø§Ø´Ø±Ø©',
    'coach.interactive': 'Ù…Ø­Ø§Ø¯Ø«Ø© ØªÙØ§Ø¹Ù„ÙŠØ©',
    'coach.quick_laugh': 'Ø¶Ø­ÙƒØ© Ø³Ø±ÙŠØ¹Ø© Ø¯Ù‚ÙŠÙ‚Ø©',
    'coach.guided_boost': 'ØªØ¹Ø²ÙŠØ² Ø§Ù„Ø·Ø§Ù‚Ø©',
    'coach.analyzing': 'ØªØ­Ù„ÙŠÙ„ Ø§Ù„ÙØ±Ø­...',
    'coach.api_missing': 'Ù…ÙØªØ§Ø­ API Ù…ÙÙ‚ÙˆØ¯!',
    'coach.offline_fallback': 'Ø§Ù„Ø¹ÙˆØ¯Ø© Ù„Ù„ÙˆØ¶Ø¹ ØºÙŠØ± Ø§Ù„Ù…ØªØµÙ„',
    'coach.joy_score': 'Ù†Ù‚Ø§Ø· Ø§Ù„ÙØ±Ø­',
    'coach.ai_listening': 'Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ ÙŠØ³ØªÙ…Ø¹...',
    'coach.listen_laugh': 'Ø§Ø³ØªÙ…Ø¹ ÙˆØ§Ø¶Ø­Ùƒ',
    'coach.listening': 'ÙŠØ³ØªÙ…Ø¹...',
    'coach.ready': 'Ø¬Ø§Ù‡Ø²',
    'coach.rate_my_laugh': 'Ù‚ÙŠÙ… Ø¶Ø­ÙƒØªÙŠ',
    'coach.stop_rate': 'ØªÙˆÙ‚Ù ÙˆÙ‚ÙŠÙ…',
    'coach.energy': 'Ø·Ø§Ù‚Ø©',
    'coach.play_again': 'Ø§Ù„Ø¹Ø¨ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰',
    'coach.offline_voice': 'ØµÙˆØª ØºÙŠØ± Ù…ØªØµÙ„ (Ù…Ø´ÙƒÙ„Ø© Ø§ØªØµØ§Ù„)',
    'coach.laughter_log': 'Ø³Ø¬Ù„ Ø§Ù„Ø¶Ø­Ùƒ',
    'coach.clear': 'Ù…Ø³Ø­',
    'coach.clear_confirm': 'Ù‡Ù„ Ø£Ù†Øª Ù…ØªØ£ÙƒØ¯ Ù…Ù† Ù…Ø³Ø­ Ø§Ù„Ø³Ø¬Ù„ØŸ',
    'coach.thanks_feedback': 'Ø´ÙƒØ±Ø§Ù‹ Ù„Ù…Ù„Ø§Ø­Ø¸Ø§ØªÙƒ!',
    'coach.session_completed': 'Ø§ÙƒØªÙ…Ù„Øª Ø§Ù„Ø¬Ù„Ø³Ø©',
    'coach.laughter_analyzed': 'ØªÙ… ØªØ­Ù„ÙŠÙ„ Ø§Ù„Ø¶Ø­Ùƒ',
    'coach.mic_permission': 'ÙŠØ±Ø¬Ù‰ Ø§Ù„Ø³Ù…Ø§Ø­ Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø§Ù„Ù…ÙŠÙƒØ±ÙˆÙÙˆÙ†!',
    'coach.analyze_error': "ØªØ¹Ø°Ø± ØªØ­Ù„ÙŠÙ„ Ø§Ù„Ø¶Ø­Ùƒ. Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰!",
    'coach.session_error': 'ØªØ¹Ø°Ø± Ø¨Ø¯Ø¡ Ø§Ù„Ø¬Ù„Ø³Ø©.',
    'coach.connection_lost': 'ÙÙ‚Ø¯ Ø§Ù„Ø§ØªØµØ§Ù„.',
    'coach.live_unavailable': 'Ù…ÙØªØ§Ø­ API Ù…ÙÙ‚ÙˆØ¯.',
  },
  fr: {
    'home.welcome': 'Allumez votre joie intÃ©rieure',
    'home.subtitle': 'Boostez l\'immunitÃ© et soulagez le stress avec les conseils d\'expert de Suman Suneja.',
    'home.test_laugh': 'Testez votre rire',
    'nav.home': 'Accueil',
    'nav.videos': 'VidÃ©os',
    'nav.games': 'Jeux',
    'nav.coach': 'Coach',
    'nav.ask_ai': 'Demander Suman',
    'profile.title': 'Votre Profil',
    'profile.subtitle': 'Personnalisez votre identitÃ©',
    'settings.title': 'ParamÃ¨tres',
    'settings.dark_mode': 'Mode Sombre',
    'settings.language': 'Langue',
    'settings.font_size': 'Taille de la police',
    'streak': 'SÃ©rie',
    'points': 'Points',
    'level': 'Niveau',
    'today': 'Aujourd\'hui',
    'save_changes': 'Sauvegarder',
    'sign_out': 'DÃ©connexion',
    'daily_session': 'Yoga du Rire Quotidien',
    'join_session': 'Rejoindre',
    'every_day': 'Chaque Jour',
    'traditional_yoga': 'Yoga Traditionnel',
    'join_yoga': 'Rejoindre le Cours',
    'mon_fri': 'Lun - Ven',
    'fun_games': 'Jeux Amusants',
    'book_session': 'RÃ©server',
    'contact': 'Contact',

    // Contact
    'contact.header_title': "Faisons de la Magie !",
    'contact.header_subtitle': "RÃ©server une sÃ©ance est la premiÃ¨re Ã©tape vers une vie plus heureuse.",
    'contact.whatsapp_btn': "WhatsApp",
    'contact.instant_reply': "RÃ©ponse InstantanÃ©e",
    'contact.email_btn': "Envoyer Email",
    'contact.for_enquiries': "Pour Renseignements",
    'contact.offerings_title': "Ce que nous offrons",
    'contact.offering_1_title': "1-sur-1",
    'contact.offering_1_desc': "Coaching Personnel",
    'contact.offering_2_title': "Entreprise",
    'contact.offering_2_desc': "Gestion du Stress",
    'contact.offering_3_title': "Groupes",
    'contact.offering_3_desc': "Ateliers",
    'contact.offering_4_title': "Retraites",
    'contact.offering_4_desc': "JournÃ©es Bien-Ãªtre",
    'contact.youtube_btn': "Voir sur YouTube",
    'contact.subscribe': "S'abonner",
    'contact.website_btn': "Visiter Site Officiel",
    'app.developed_by': "App DÃ©veloppÃ©e par",

    // Profile
    'profile.display_name': "Nom d'affichage",
    'profile.enter_name_placeholder': "Entrez votre nom",
    'profile.phone_number': "NumÃ©ro de tÃ©lÃ©phone",
    'profile.no_number': "Aucun numÃ©ro liÃ©",
    'profile.streak_power': "PUISSANCE DE SÃ‰RIE",
    'profile.streak_power_description': "Gardez votre sÃ©rie de rires vivante pour dÃ©bloquer des badges exclusifs et du contenu premium !",
    'profile.start_today': "Commencez aujourd'hui !",
    'profile.bonus': "Bonus",
    'profile.personal_info': "Infos Personnelles",
    'profile.edit_button': "Modifier",
    'profile.link_button': "Lier",

    // Games
    'games.title': "Labo de Rire IA",
    'games.subtitle_jokes': "GÃ©nÃ©rateur de Blagues",
    'games.subtitle_joy': "GÃ©nÃ©rateur de Joie",
    'games.tab_story': "Histoire",
    'games.tab_jokes': "Blagues",
    'games.tab_moods': "Humeurs",
    'games.speaking': "Parle...",
    'games.writing_joke': "Ã‰crit une blague...",
    'games.brewing_laughter': "PrÃ©pare le rire...",
    'games.funny_mode': "Mode DrÃ´le",
    'games.ai_mode': "Mode IA",
    'games.play_real_laughter': "Jouer Rire RÃ©el",
    'games.offline_voice': "Voix Hors Ligne",
    'games.input_placeholder_story': "Situation (ex. RÃ©veil ratÃ©)",
    'games.input_placeholder_joke': "Sujet (ex. Chats, Patron, CafÃ©)",
    'games.input_placeholder_mood': "Choisissez une humeur.",
    'games.btn_joke': "Raconte une blague !",
    'games.btn_story': "GÃ©nÃ©rer Histoire de Joie",
    'games.stop_audio': "ArrÃªter Audio",
    'games.mood_giggle': "Gloussement",
    'games.mood_belly': "Rire de ventre",
    'games.mood_snort': "Rire cochon",
    'games.mood_cackle': "Rire de sorciÃ¨re",

    // Video Library
    'video.title': 'VidÃ©othÃ¨que',
    'video.visit_channel': 'Visiter ChaÃ®ne Officielle',
    'video.count_suffix': 'VidÃ©os',
    'video.tab_all': 'Toutes',
    'video.tab_favorites': 'Favoris',
    'video.tab_offline': 'Hors ligne',
    'video.search_placeholder': 'Rechercher vidÃ©os...',
    'video.filter_all': 'Tous',
    'video.no_videos': 'Aucune vidÃ©o trouvÃ©e',
    'video.now_playing': 'Lecture en cours',
    'video.open_app': 'Ouvrir dans l\'app',
    'video.save_offline': 'Sauvegarder',
    'video.saving': 'Enregistrement...',
    'video.saved': 'EnregistrÃ©',
    'video.remove_confirm': 'Supprimer de la bibliothÃ¨que hors ligne ?',
    'video.saved_toast': 'VidÃ©o enregistrÃ©e hors ligne',
    'video.started_toast': 'Session vidÃ©o commencÃ©e',
    'video.page': 'Page',
    'video.of': 'de',
    'video.category_events': 'Ã‰vÃ©nements',
    'video.category_corporate': 'Entreprise',
    'video.category_health': 'SantÃ©',
    'video.category_exercises': 'Exercices',
    'video.category_fun': 'Amusement',
    'video.category_morning': 'Matin',
    'video.category_meditation': 'MÃ©ditation',
    'video.category_stress_relief': 'Gestion du Stress',
    'video.category_daily': 'Quotidien',
    'video.category_sessions': 'SÃ©ances',
    'video.category_seniors': 'SÃ©niors',

    // Laughter Coach
    'coach.title': 'Coach de Rire',
    'coach.subtitle': 'Riez fort pour obtenir votre score de bonheur !',
    'coach.how_was_it': 'C\'Ã©tait comment ?',
    'coach.help_improve': 'Aidez Suman AI Ã  s\'amÃ©liorer !',
    'coach.skip_feedback': 'Passer',
    'coach.start_live': 'DÃ©marrer Session Live',
    'coach.interactive': 'Conversation Interactive',
    'coach.quick_laugh': 'Rire Rapide 1-Min',
    'coach.guided_boost': 'Boost d\'Ã‰nergie GuidÃ©',
    'coach.analyzing': 'Analyse de la Joie...',
    'coach.api_missing': 'ClÃ© API Gemini Manquante !',
    'coach.offline_fallback': 'Passage en mode hors ligne',
    'coach.joy_score': 'Score de Joie',
    'coach.ai_listening': 'IA Ã‰coute...',
    'coach.listen_laugh': 'Ã‰coutez et Riez',
    'coach.listening': 'Ã‰coute...',
    'coach.ready': 'PrÃªt',
    'coach.rate_my_laugh': 'Noter mon Rire',
    'coach.stop_rate': 'ArrÃªter et Noter',
    'coach.energy': 'Ã‰nergie',
    'coach.play_again': 'Rejouer',
    'coach.offline_voice': 'Utilisation Voix Hors Ligne (ProblÃ¨me Connexion)',
    'coach.laughter_log': 'Journal de Rire',
    'coach.clear': 'Effacer',
    'coach.clear_confirm': 'Voulez-vous vraiment effacer votre journal ?',
    'coach.thanks_feedback': 'Merci pour vos commentaires !',
    'coach.session_completed': 'Session TerminÃ©e',
    'coach.laughter_analyzed': 'Rire AnalysÃ©',
    'coach.mic_permission': 'Veuillez autoriser l\'accÃ¨s au micro !',
    'coach.analyze_error': "Impossible d'analyser le rire. RÃ©essayez !",
    'coach.session_error': 'Impossible de dÃ©marrer la session.',
    'coach.connection_lost': 'Connexion perdue.',
    'coach.live_unavailable': 'ClÃ© API manquante. Session live indisponible.',
  },
  de: {
    'home.welcome': 'Entfache deine innere Freude',
    'home.subtitle': 'StÃ¤rke dein Immunsystem und baue Stress ab mit Expertenrat von Suman Suneja.',
    'home.test_laugh': 'Teste dein Lachen',
    'nav.home': 'Start',
    'nav.videos': 'Videos',
    'nav.games': 'Spiele',
    'nav.coach': 'Coach',
    'nav.ask_ai': 'Frag Suman',
    'profile.title': 'Dein Profil',
    'profile.subtitle': 'Personalisiere deine IdentitÃ¤t',
    'settings.title': 'Einstellungen',
    'settings.dark_mode': 'Dunkelmodus',
    'settings.language': 'Sprache',
    'settings.font_size': 'SchriftgrÃ¶ÃŸe',
    'streak': 'Serie',
    'points': 'Punkte',
    'level': 'Level',
    'today': 'Heute',
    'save_changes': 'Speichern',
    'sign_out': 'Abmelden',
    'daily_session': 'TÃ¤gliches Lachyoga',
    'join_session': 'Beitreten',
    'every_day': 'TÃ¤glich',
    'traditional_yoga': 'Traditionelles Yoga',
    'join_yoga': 'Kurs beitreten',
    'mon_fri': 'Mo - Fr',
    'fun_games': 'Lustige Spiele',
    'book_session': 'Sitzung buchen',
    'contact': 'Kontakt',

    // Contact
    'contact.header_title': "Lass uns Magie machen!",
    'contact.header_subtitle': "Eine Sitzung zu buchen ist der erste Schritt zu einem glÃ¼cklicheren Leben.",
    'contact.whatsapp_btn': "WhatsApp uns",
    'contact.instant_reply': "Sofortantwort",
    'contact.email_btn': "E-Mail senden",
    'contact.for_enquiries': "FÃ¼r Anfragen",
    'contact.offerings_title': "Was wir bieten",
    'contact.offering_1_title': "1-zu-1",
    'contact.offering_1_desc': "PersÃ¶nliches Coaching",
    'contact.offering_2_title': "Firmen",
    'contact.offering_2_desc': "Stressabbau",
    'contact.offering_3_title': "Gruppen",
    'contact.offering_3_desc': "Workshops",
    'contact.offering_4_title': "Retreats",
    'contact.offering_4_desc': "Wellness-Tage",
    'contact.youtube_btn': "Auf YouTube ansehen",
    'contact.subscribe': "Abonnieren",
    'contact.website_btn': "Offizielle Website",
    'app.developed_by': "App entwickelt von",

    // Profile
    'profile.display_name': "Anzeigename",
    'profile.enter_name_placeholder': "Name eingeben",
    'profile.phone_number': "Telefonnummer",
    'profile.no_number': "Keine Nummer verknÃ¼pft",
    'profile.streak_power': "SERIEN-POWER",
    'profile.streak_power_description': "Halte deine Lachserie am Leben, um exklusive Abzeichen und Premium-Inhalte freizuschalten!",
    'profile.start_today': "Starte heute!",
    'profile.bonus': "Bonus",
    'profile.personal_info': "PersÃ¶nliche Infos",
    'profile.edit_button': "Bearbeiten",
    'profile.link_button': "VerknÃ¼pfen",

    // Games
    'games.title': "KI-Lachlabor",
    'games.subtitle_jokes': "Witz-Generator",
    'games.subtitle_joy': "Freude-Generator",
    'games.tab_story': "Geschichte",
    'games.tab_jokes': "Witze",
    'games.tab_moods': "Launen",
    'games.speaking': "Spricht...",
    'games.writing_joke': "Schreibt einen Witz...",
    'games.brewing_laughter': "Braut GelÃ¤chter...",
    'games.funny_mode': "Lustiger Modus",
    'games.ai_mode': "KI-Modus",
    'games.play_real_laughter': "Echtes Lachen abspielen",
    'games.offline_voice': "Offline-Stimme",
    'games.input_placeholder_story': "Situation (z.B. Wecker verpasst)",
    'games.input_placeholder_joke': "Thema (z.B. Katzen, Chef, Kaffee)",
    'games.input_placeholder_mood': "WÃ¤hle eine Stimmung.",
    'games.btn_joke': "ErzÃ¤hl mir einen Witz!",
    'games.btn_story': "Freudengeschichte generieren",
    'games.stop_audio': "Audio stoppen",
    'games.mood_giggle': "Kichern",
    'games.mood_belly': "Bauchlachen",
    'games.mood_snort': "Grunzlachen",
    'games.mood_cackle': "Hexenlachen",

    // Video Library
    'video.title': 'Videothek',
    'video.visit_channel': 'Offiziellen Kanal besuchen',
    'video.count_suffix': 'Videos',
    'video.tab_all': 'Alle Videos',
    'video.tab_favorites': 'Favoriten',
    'video.tab_offline': 'Offline',
    'video.search_placeholder': 'Videos suchen...',
    'video.filter_all': 'Alle',
    'video.no_videos': 'Keine Videos gefunden',
    'video.now_playing': 'LÃ¤uft gerade',
    'video.open_app': 'In App Ã¶ffnen',
    'video.save_offline': 'Offline speichern',
    'video.saving': 'Speichern...',
    'video.saved': 'Gespeichert',
    'video.remove_confirm': 'Aus Offline-Bibliothek entfernen?',
    'video.saved_toast': 'Offline-Video gespeichert',
    'video.started_toast': 'Videositzung gestartet',
    'video.page': 'Seite',
    'video.of': 'von',
    'video.category_events': 'Veranstaltungen',
    'video.category_corporate': 'Firmen',
    'video.category_health': 'Gesundheit',
    'video.category_exercises': 'Ãœbungen',
    'video.category_fun': 'SpaÃŸ',
    'video.category_morning': 'Morgen',
    'video.category_meditation': 'Meditation',
    'video.category_stress_relief': 'Stressabbau',
    'video.category_daily': 'TÃ¤glich',
    'video.category_sessions': 'Sitzungen',
    'video.category_seniors': 'Senioren',

    // Laughter Coach
    'coach.title': 'Lach-Coach',
    'coach.subtitle': 'Lache laut, um deinen GlÃ¼ckswert zu erhalten!',
    'coach.how_was_it': 'Wie war es?',
    'coach.help_improve': 'Hilf Suman AI besser zu werden!',
    'coach.skip_feedback': 'Ãœberspringen',
    'coach.start_live': 'Live-Sitzung starten',
    'coach.interactive': 'Interaktives GesprÃ¤ch',
    'coach.quick_laugh': 'Schnelles 1-Min Lachen',
    'coach.guided_boost': 'GefÃ¼hrter Energieschub',
    'coach.analyzing': 'Analysiere Freude...',
    'coach.api_missing': 'Gemini API-SchlÃ¼ssel fehlt!',
    'coach.offline_fallback': 'Wechsle in Offline-Modus',
    'coach.joy_score': 'Freude-Score',
    'coach.ai_listening': 'KI hÃ¶rt zu...',
    'coach.listen_laugh': 'ZuhÃ¶ren & Lachen',
    'coach.listening': 'HÃ¶rt zu...',
    'coach.ready': 'Bereit',
    'coach.rate_my_laugh': 'Bewerte mein Lachen',
    'coach.stop_rate': 'Stopp & Bewerten',
    'coach.energy': 'Energie',
    'coach.play_again': 'Nochmal spielen',
    'coach.offline_voice': 'Offline-Stimme (Verbindungsproblem)',
    'coach.laughter_log': 'Lach-Protokoll',
    'coach.clear': 'LÃ¶schen',
    'coach.clear_confirm': 'MÃ¶chtest du dein Protokoll wirklich lÃ¶schen?',
    'coach.thanks_feedback': 'Danke fÃ¼r dein Feedback!',
    'coach.session_completed': 'Sitzung beendet',
    'coach.laughter_analyzed': 'Lachen analysiert',
    'coach.mic_permission': 'Bitte erlaube Mikrofonzugriff!',
    'coach.analyze_error': "Konnte Lachen nicht analysieren. Versuch es nochmal!",
    'coach.session_error': 'Konnte Sitzung nicht starten.',
    'coach.connection_lost': 'Verbindung verloren.',
    'coach.live_unavailable': 'API-SchlÃ¼ssel fehlt. Live-Sitzung nicht verfÃ¼gbar.',
  },
  ja: {
    'home.welcome': 'å†…ãªã‚‹å–œã³ã‚’ç‚¹ç«ã—ã‚ˆã†',
    'home.subtitle': 'Suman Sunejaã®å°‚é–€çš„ãªæŒ‡å°Žã§å…ç–«åŠ›ã‚’é«˜ã‚ã€ã‚¹ãƒˆãƒ¬ã‚¹ã‚’è§£æ¶ˆã—ã¾ã—ã‚‡ã†ã€‚',
    'home.test_laugh': 'ç¬‘ã„ã‚’ãƒ†ã‚¹ãƒˆ',
    'nav.home': 'ãƒ›ãƒ¼ãƒ ',
    'nav.videos': 'å‹•ç”»',
    'nav.games': 'ã‚²ãƒ¼ãƒ ',
    'nav.coach': 'ã‚³ãƒ¼ãƒ',
    'nav.ask_ai': 'Sumanã«èžã',
    'profile.title': 'ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«',
    'profile.subtitle': 'å–œã³ã®IDã‚’ã‚«ã‚¹ã‚¿ãƒžã‚¤ã‚º',
    'settings.title': 'è¨­å®š',
    'settings.dark_mode': 'ãƒ€ãƒ¼ã‚¯ãƒ¢ãƒ¼ãƒ‰',
    'settings.language': 'è¨€èªž',
    'settings.font_size': 'æ–‡å­—ã‚µã‚¤ã‚º',
    'streak': 'é€£ç¶šè¨˜éŒ²',
    'points': 'ãƒã‚¤ãƒ³ãƒˆ',
    'level': 'ãƒ¬ãƒ™ãƒ«',
    'today': 'ä»Šæ—¥',
    'save_changes': 'ä¿å­˜',
    'sign_out': 'ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ',
    'daily_session': 'æ¯Žæ—¥ã®ãƒ©ãƒ•ã‚¿ãƒ¼ãƒ¨ã‚¬',
    'join_session': 'å‚åŠ ã™ã‚‹',
    'every_day': 'æ¯Žæ—¥',
    'traditional_yoga': 'ä¼çµ±çš„ï¼†ãƒ©ãƒ•ã‚¿ãƒ¼ãƒ¨ã‚¬',
    'join_yoga': 'ã‚¯ãƒ©ã‚¹ã«å‚åŠ ',
    'mon_fri': 'æœˆ - é‡‘',
    'fun_games': 'æ¥½ã—ã„ã‚²ãƒ¼ãƒ ',
    'book_session': 'ã‚»ãƒƒã‚·ãƒ§ãƒ³äºˆç´„',
    'contact': 'é€£çµ¡å…ˆ',

    // Contact
    'contact.header_title': "é­”æ³•ã‚’èµ·ã“ãã†ï¼",
    'contact.header_subtitle': "ã‚»ãƒƒã‚·ãƒ§ãƒ³ã®äºˆç´„ã¯ã€ã‚ˆã‚Šå¹¸ã›ã§å¥åº·çš„ãªç”Ÿæ´»ã¸ã®ç¬¬ä¸€æ­©ã§ã™ã€‚",
    'contact.whatsapp_btn': "WhatsApp",
    'contact.instant_reply': "å³æ™‚è¿”ä¿¡",
    'contact.email_btn': "ãƒ¡ãƒ¼ãƒ«ã‚’é€ã‚‹",
    'contact.for_enquiries': "ãŠå•ã„åˆã‚ã›",
    'contact.offerings_title': "æä¾›ã‚µãƒ¼ãƒ“ã‚¹",
    'contact.offering_1_title': "ãƒžãƒ³ãƒ„ãƒ¼ãƒžãƒ³",
    'contact.offering_1_desc': "ãƒ‘ãƒ¼ã‚½ãƒŠãƒ«ã‚³ãƒ¼ãƒãƒ³ã‚°",
    'contact.offering_2_title': "ä¼æ¥­å‘ã‘",
    'contact.offering_2_desc': "ã‚¹ãƒˆãƒ¬ã‚¹è§£æ¶ˆ",
    'contact.offering_3_title': "ã‚°ãƒ«ãƒ¼ãƒ—",
    'contact.offering_3_desc': "ãƒ¯ãƒ¼ã‚¯ã‚·ãƒ§ãƒƒãƒ—",
    'contact.offering_4_title': "ãƒªãƒˆãƒªãƒ¼ãƒˆ",
    'contact.offering_4_desc': "ã‚¦ã‚§ãƒ«ãƒã‚¹ãƒ‡ãƒ¼",
    'contact.youtube_btn': "YouTubeã§è¦‹ã‚‹",
    'contact.subscribe': "ç™»éŒ²ã™ã‚‹",
    'contact.website_btn': "å…¬å¼ã‚µã‚¤ãƒˆã¸",
    'app.developed_by': "ã‚¢ãƒ—ãƒªé–‹ç™º",

    // Profile
    'profile.display_name': "è¡¨ç¤ºå",
    'profile.enter_name_placeholder': "åå‰ã‚’å…¥åŠ›",
    'profile.phone_number': "é›»è©±ç•ªå·",
    'profile.no_number': "ç•ªå·ãŒãƒªãƒ³ã‚¯ã•ã‚Œã¦ã„ã¾ã›ã‚“",
    'profile.streak_power': "ã‚¹ãƒˆãƒªãƒ¼ã‚¯ãƒ‘ãƒ¯ãƒ¼",
    'profile.streak_power_description': "ã‚¹ãƒˆãƒªãƒ¼ã‚¯ã‚’ç¶­æŒã—ã¦ã€é™å®šãƒãƒƒã‚¸ã‚„ãƒ—ãƒ¬ãƒŸã‚¢ãƒ ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã‚’è§£é™¤ã—ã‚ˆã†ï¼",
    'profile.start_today': "ä»Šæ—¥ã‹ã‚‰å§‹ã‚ã‚ˆã†ï¼",
    'profile.bonus': "ãƒœãƒ¼ãƒŠã‚¹",
    'profile.personal_info': "å€‹äººæƒ…å ±",
    'profile.edit_button': "ç·¨é›†",
    'profile.link_button': "ãƒªãƒ³ã‚¯",

    // Games
    'games.title': "AIãƒ©ãƒ•ã‚¿ãƒ¼ãƒ©ãƒœ",
    'games.subtitle_jokes': "ä¸€è¡Œã‚¸ãƒ§ãƒ¼ã‚¯ç”Ÿæˆ",
    'games.subtitle_joy': "å®Ÿé¨“çš„å–œã³ç”Ÿæˆ",
    'games.tab_story': "ã‚¹ãƒˆãƒ¼ãƒªãƒ¼",
    'games.tab_jokes': "ã‚¸ãƒ§ãƒ¼ã‚¯",
    'games.tab_moods': "æ°—åˆ†",
    'games.speaking': "è©±ã—ã¦ã„ã¾ã™...",
    'games.writing_joke': "ã‚¸ãƒ§ãƒ¼ã‚¯ã‚’æ›¸ã„ã¦ã„ã¾ã™...",
    'games.brewing_laughter': "ç¬‘ã„ã‚’é†¸é€ ä¸­...",
    'games.funny_mode': "é¢ç™½ã„ãƒ¢ãƒ¼ãƒ‰",
    'games.ai_mode': "AIãƒ¢ãƒ¼ãƒ‰",
    'games.play_real_laughter': "ãƒªã‚¢ãƒ«ãªç¬‘ã„ã‚’å†ç”Ÿ",
    'games.offline_voice': "ã‚ªãƒ•ãƒ©ã‚¤ãƒ³éŸ³å£°",
    'games.input_placeholder_story': "çŠ¶æ³ï¼ˆä¾‹ï¼šç›®è¦šã¾ã—æ™‚è¨ˆã®å¤±æ•—ï¼‰",
    'games.input_placeholder_joke': "ãƒˆãƒ”ãƒƒã‚¯ï¼ˆä¾‹ï¼šçŒ«ã€ä¸Šå¸ã€ã‚³ãƒ¼ãƒ’ãƒ¼ï¼‰",
    'games.input_placeholder_mood': "æ°—åˆ†ã‚’é¸ã‚“ã§ç¬‘ã„ã‚’èžã",
    'games.btn_joke': "ã‚¸ãƒ§ãƒ¼ã‚¯ã‚’è¨€ã£ã¦ç¬‘ã‚ã›ã¦ï¼",
    'games.btn_story': "å–œã³ã®ã‚¹ãƒˆãƒ¼ãƒªãƒ¼ã‚’ç”Ÿæˆ",
    'games.stop_audio': "éŸ³å£°ã‚’åœæ­¢",
    'games.mood_giggle': "ãã™ãã™ç¬‘ã„",
    'games.mood_belly': "è…¹ã®åº•ã‹ã‚‰ã®ç¬‘ã„",
    'games.mood_snort': "é¼»ã‚’é³´ã‚‰ã™ç¬‘ã„",
    'games.mood_cackle': "é­”å¥³ã®ç¬‘ã„",

    // Video Library
    'video.title': 'ãƒ“ãƒ‡ã‚ªãƒ©ã‚¤ãƒ–ãƒ©ãƒª',
    'video.visit_channel': 'å…¬å¼ãƒãƒ£ãƒ³ãƒãƒ«',
    'video.count_suffix': 'å‹•ç”»',
    'video.tab_all': 'ã™ã¹ã¦',
    'video.tab_favorites': 'ãŠæ°—ã«å…¥ã‚Š',
    'video.tab_offline': 'ã‚ªãƒ•ãƒ©ã‚¤ãƒ³',
    'video.search_placeholder': 'å‹•ç”»ã‚’æ¤œç´¢...',
    'video.filter_all': 'ã™ã¹ã¦',
    'video.no_videos': 'å‹•ç”»ãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“',
    'video.now_playing': 'å†ç”Ÿä¸­',
    'video.open_app': 'ã‚¢ãƒ—ãƒªã§é–‹ã',
    'video.save_offline': 'ä¿å­˜',
    'video.saving': 'ä¿å­˜ä¸­...',
    'video.saved': 'ä¿å­˜æ¸ˆã¿',
    'video.remove_confirm': 'ã‚ªãƒ•ãƒ©ã‚¤ãƒ³ãƒ©ã‚¤ãƒ–ãƒ©ãƒªã‹ã‚‰å‰Šé™¤ã—ã¾ã™ã‹ï¼Ÿ',
    'video.saved_toast': 'ã‚ªãƒ•ãƒ©ã‚¤ãƒ³ã«ä¿å­˜ã—ã¾ã—ãŸ',
    'video.started_toast': 'ã‚»ãƒƒã‚·ãƒ§ãƒ³é–‹å§‹',
    'video.page': 'ãƒšãƒ¼ã‚¸',
    'video.of': '/',
    'video.category_events': 'ã‚¤ãƒ™ãƒ³ãƒˆ',
    'video.category_corporate': 'ä¼æ¥­å‘ã‘',
    'video.category_health': 'å¥åº·',
    'video.category_exercises': 'ã‚¨ã‚¯ã‚µã‚µã‚¤ã‚º',
    'video.category_fun': 'æ¥½ã—ã„',
    'video.category_morning': 'æœ',
    'video.category_meditation': 'çž‘æƒ³',
    'video.category_stress_relief': 'ã‚¹ãƒˆãƒ¬ã‚¹è§£æ¶ˆ',
    'video.category_daily': 'æ¯Žæ—¥',
    'video.category_sessions': 'ã‚»ãƒƒã‚·ãƒ§ãƒ³',
'video.category_seniors': 'ã‚·ãƒ‹ã‚¢',

    // Laughter Coach
    'coach.title': 'ãƒ©ãƒ•ã‚¿ãƒ¼ã‚³ãƒ¼ãƒ',
        'coach.subtitle': 'å¤§å£°ã§ç¬‘ã£ã¦ãƒãƒƒãƒ”ãƒ¼ã‚¹ã‚³ã‚¢ã‚’ã‚²ãƒƒãƒˆï¼',
            'coach.how_was_it': 'ã©ã†ã§ã—ãŸã‹ï¼Ÿ',
                'coach.help_improve': 'Suman AIã®æ”¹å–„ã«ã”å”åŠ›ãã ã•ã„ï¼',
                    'coach.skip_feedback': 'ã‚¹ã‚­ãƒƒãƒ—',
                        'coach.start_live': 'ãƒ©ã‚¤ãƒ–ã‚»ãƒƒã‚·ãƒ§ãƒ³é–‹å§‹',
                            'coach.interactive': 'å¯¾è©±ãƒ¢ãƒ¼ãƒ‰',
                                'coach.quick_laugh': '1åˆ†é–“ã‚¯ã‚¤ãƒƒã‚¯ç¬‘ã„',
                                    'coach.guided_boost': 'ã‚¨ãƒãƒ«ã‚®ãƒ¼ãƒ–ãƒ¼ã‚¹ãƒˆ',
                                        'coach.analyzing': 'å–œã³ã‚’åˆ†æžä¸­...',
                                            'coach.api_missing': 'APIã‚­ãƒ¼ãŒã‚ã‚Šã¾ã›ã‚“ï¼',
                                                'coach.offline_fallback': 'ã‚ªãƒ•ãƒ©ã‚¤ãƒ³ãƒ¢ãƒ¼ãƒ‰',
                                                    'coach.joy_score': 'ã‚¸ãƒ§ã‚¤ã‚¹ã‚³ã‚¢',
                                                        'coach.ai_listening': 'AIãŒèžã„ã¦ã„ã¾ã™...',
                                                            'coach.listen_laugh': 'èžã„ã¦ç¬‘ãŠã†',
                                                                'coach.listening': 'èžã„ã¦ã„ã¾ã™...',
                                                                    'coach.ready': 'æº–å‚™å®Œäº†',
                                                                        'coach.laughter_log': 'ç¬‘ã„ã®è¨˜éŒ²',
                                                                            'coach.clear': 'æ¶ˆåŽ»',
                                                                                'coach.clear_confirm': 'è¨˜éŒ²ã‚’æ¶ˆåŽ»ã—ã¾ã™ã‹ï¼Ÿ',
                                                                                    'coach.thanks_feedback': 'ãƒ•ã‚£ãƒ¼ãƒ‰ãƒãƒƒã‚¯ã‚ã‚ŠãŒã¨ã†ã”ã–ã„ã¾ã™ï¼',
                                                                                        'coach.session_completed': 'ã‚»ãƒƒã‚·ãƒ§ãƒ³å®Œäº†',
                                                                                            'coach.laughter_analyzed': 'ç¬‘ã„ã‚’åˆ†æžã—ã¾ã—ãŸ',
                                                                                                'coach.mic_permission': 'ãƒžã‚¤ã‚¯ã®ä½¿ç”¨ã‚’è¨±å¯ã—ã¦ãã ã•ã„ï¼',
                                                                                                    'coach.analyze_error': "åˆ†æžã§ãã¾ã›ã‚“ã§ã—ãŸã€‚å†è©¦è¡Œã—ã¦ãã ã•ã„ã€‚",
                                                                                                        'coach.session_error': 'ã‚»ãƒƒã‚·ãƒ§ãƒ³ã‚’é–‹å§‹ã§ãã¾ã›ã‚“ã€‚',
                                                                                                            'coach.connection_lost': 'æŽ¥ç¶šãŒåˆ‡ã‚Œã¾ã—ãŸã€‚',
                                                                                                                'coach.live_unavailable': 'APIã‚­ãƒ¼ãŒã‚ã‚Šã¾ã›ã‚“ã€‚',
  }
};

export interface ThemeColors {
    HERO: string;
    HERO_BUTTON: string;
    BUTTON: string;
    BUTTON_SECONDARY: string;
    GAMES: string;
    GAMES_ICON_BG: string;
    BOOK: string;
    BOOK_ICON_BG: string;
    TEXT_PRIMARY: string;
    ICON_BG: string;
    ICON_COLOR: string;
    STAT_BG_1: string;
    STAT_ICON_BG_1: string;
    STAT_BG_2: string;
    STAT_ICON_BG_2: string;
    LIVE_CARD_BG: string;
    LIVE_BTN: string;
    // Header
    HEADER_BG: string;
    HEADER_TEXT: string;
    HEADER_BORDER: string;
    SUBSCRIBE_BTN: string;
    // Music
    MUSIC_BTN: string;
    MUSIC_BTN_ACTIVE: string;
    MUSIC_ICON: string;
    // Mic
    MIC_BTN: string;
    MIC_RIPPLE: string;
    // Video Library
    VIDEO_BG: string;
    INPUT_RING: string;
    LOADING_SPINNER: string;
    TEXT_ACCENT: string;
    VIDEO_RING_1: string;
    VIDEO_RING_2: string;
    VIDEO_BORDER: string;
}

export const THEMES: Record<ColorTheme, ThemeColors> = {
    pastel: {
        HERO: "bg-[#A9A9C6]",
        HERO_BUTTON: "bg-white text-[#A9A9C6] shadow-sm hover:bg-gray-50 border-none",
        BUTTON: "bg-[#A8C8C0] text-white shadow-sm hover:brightness-105 border-none",
        BUTTON_SECONDARY: "bg-[#C0B8D0] text-white shadow-sm hover:brightness-105 border-none",
        GAMES: "bg-[#EFEFF5] text-[#5B5166] border-none",
        GAMES_ICON_BG: "bg-[#B8B8D0] text-white p-3 rounded-full mb-1",
        BOOK: "bg-[#EFEFF5] text-[#5B5166] border-none",
        BOOK_ICON_BG: "bg-[#A0B0B0] text-white p-3 rounded-full mb-1",
        TEXT_PRIMARY: "text-[#5B5166]",
        ICON_BG: "bg-[#E8DFF5]",
        ICON_COLOR: "text-[#9B86BD]",
        STAT_BG_1: "bg-[#FFF0E0] border border-orange-100",
        STAT_ICON_BG_1: "bg-white text-orange-400",
        STAT_BG_2: "bg-[#F0F0FF] border border-purple-100",
        STAT_ICON_BG_2: "bg-white text-purple-400",
        LIVE_CARD_BG: "bg-white border-2 border-purple-100",
        LIVE_BTN: "bg-[#A8C8C0] text-white hover:brightness-105 shadow-md",
        // Header
        HEADER_BG: "bg-[#EFEFF5]",
        HEADER_TEXT: "text-[#5B5166]",
        HEADER_BORDER: "border-[#B8B8D0]/20",
        SUBSCRIBE_BTN: "bg-[#C0B8D0] hover:bg-[#B0A8C0]",
        // Music
        MUSIC_BTN: "bg-white border-[#EDE8F8] text-[#C3B8D5] hover:border-[#A8C8C0] hover:text-[#A8C8C0]",
        MUSIC_BTN_ACTIVE: "bg-[#A8C8C0] border-white text-white",
        MUSIC_ICON: "text-[#A8C8C0]",
        // Mic
        MIC_BTN: "bg-[#C0B8D0] text-white hover:scale-110",
        MIC_RIPPLE: "bg-[#C0B8D0]/30",
        // Video Library
        VIDEO_BG: "bg-[#FEF4E6]",
        INPUT_RING: "focus:ring-[#ABCEC9]",
        LOADING_SPINNER: "border-[#ABCEC9]",
        TEXT_ACCENT: "text-[#ABCEC9]",
        VIDEO_RING_1: "bg-[#C0B8D0]/20",
        VIDEO_RING_2: "bg-[#C0B8D0]/40",
        VIDEO_BORDER: "border-[#C0B8D0]/50"
    },
    red_brick: {
        HERO: "bg-[linear-gradient(110deg,#592E2E_0%,#8C4A4A_50%,#592E2E_100%)]",
        HERO_BUTTON: "bg-[linear-gradient(135deg,#8B3A3A_0%,#B85C5C_50%,#8B3A3A_100%)] text-white shadow-lg border border-white/20",
        BUTTON: "bg-[linear-gradient(135deg,#8B3A3A_0%,#B85C5C_50%,#8B3A3A_100%)] text-white shadow-[0_4px_20px_rgba(139,58,58,0.4)] hover:brightness-110 border-none",
        BUTTON_SECONDARY: "bg-[linear-gradient(135deg,#8B3A3A_0%,#B85C5C_50%,#8B3A3A_100%)] text-white shadow-[0_4px_20px_rgba(139,58,58,0.4)] hover:brightness-110 border-none",
        GAMES: "bg-[linear-gradient(135deg,#8B3A3A_0%,#B85C5C_50%,#8B3A3A_100%)] text-white border-2 border-white/20",
        GAMES_ICON_BG: "text-white mb-1",
        BOOK: "bg-[linear-gradient(135deg,#8B3A3A_0%,#B85C5C_50%,#8B3A3A_100%)] text-white border-2 border-white/20",
        BOOK_ICON_BG: "text-white mb-1",
        TEXT_PRIMARY: "text-[#934139]",
        ICON_BG: "bg-pink-100",
        ICON_COLOR: "text-pink-500",
        STAT_BG_1: "bg-[#FFF8F0] border border-orange-100",
        STAT_ICON_BG_1: "bg-white text-orange-500",
        STAT_BG_2: "bg-[#F8F0FF] border border-purple-100",
        STAT_ICON_BG_2: "bg-white text-purple-500",
        LIVE_CARD_BG: "bg-white/70 backdrop-blur-xl border-2 border-purple-300/50",
        LIVE_BTN: "bg-[linear-gradient(135deg,#8B3A3A_0%,#B85C5C_50%,#8B3A3A_100%)] text-white shadow-lg shadow-teal-700/20",
        // Header
        HEADER_BG: "bg-[#FEF4E6]",
        HEADER_TEXT: "text-[#783766]",
        HEADER_BORDER: "border-[#783766]/10",
        SUBSCRIBE_BTN: "bg-[#934139] hover:bg-[#7a302a]",
        // Music
        MUSIC_BTN: "bg-white border-[#EDE8F8] text-[#C3B8D5] hover:border-[#8B3A3A] hover:text-[#8B3A3A]",
        MUSIC_BTN_ACTIVE: "bg-[#8B3A3A] border-white text-white",
        MUSIC_ICON: "text-[#8B3A3A]",
        // Mic
        MIC_BTN: "bg-[linear-gradient(135deg,#8B3A3A_0%,#B85C5C_50%,#8B3A3A_100%)] text-white hover:scale-110",
        MIC_RIPPLE: "bg-[#8B3A3A]/30",
        // Video Library
        VIDEO_BG: "bg-[#FEF4E6]",
        INPUT_RING: "focus:ring-[#8B3A3A]",
        LOADING_SPINNER: "border-[#8B3A3A]",
        TEXT_ACCENT: "text-[#8B3A3A]",
        VIDEO_RING_1: "bg-[#8B3A3A]/20",
        VIDEO_RING_2: "bg-[#8B3A3A]/40",
        VIDEO_BORDER: "border-[#8B3A3A]/50"
    }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('app_theme') as Theme) || 'light');
    const [colorTheme, setColorTheme] = useState<ColorTheme>(() => (localStorage.getItem('app_color_theme') as ColorTheme) || 'red_brick');
    const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('app_lang') as Language) || 'en');
    const [fontSize, setFontSize] = useState<FontSize>(() => (localStorage.getItem('app_fontsize') as FontSize) || 'normal');
    const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr');

    const currentTheme = THEMES[colorTheme] || THEMES.red_brick;

    useEffect(() => {
        localStorage.setItem('app_theme', theme);
        if (theme === 'dark') {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    }, [theme]);

    useEffect(() => {
        localStorage.setItem('app_color_theme', colorTheme);
    }, [colorTheme]);

    useEffect(() => {
        localStorage.setItem('app_lang', language);
        document.documentElement.lang = language;
        const direction = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.dir = direction;
        setDir(direction);
    }, [language]);

    useEffect(() => {
        localStorage.setItem('app_fontsize', fontSize);
        const sizeMap = {
            small: '14px',
            normal: '16px',
            large: '19px',
            xl: '22px'
        };
        document.documentElement.style.fontSize = sizeMap[fontSize];
    }, [fontSize]);

    const toggleTheme = () => setTheme(prev => prev === 'light' ? 'dark' : 'light');

    const t = (key: string) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <SettingsContext.Provider value={{ theme, toggleTheme, colorTheme, setColorTheme, currentTheme, language, setLanguage, fontSize, setFontSize, t, dir }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (!context) throw new Error('useSettings must be used within SettingsProvider');
    return context;
};
