export const JOKES = [
    { id: 'j1', title: 'Doctor Visit', text: "I told my doctor I broke my arm in two places. He told me to stop going to those places! Hahaha!" },
    { id: 'j2', title: 'Trust Issues', text: "Why don't scientists trust atoms? Because they make up everything! Hee hee hee!" },
    { id: 'j3', title: 'Seafood Diet', text: "I'm on a seafood diet. I see food and I eat it! Hahaha!" },
    { id: 'j4', title: 'Outstanding', text: "Why was the scarecrow an award-winning employee? Because he was outstanding in his field! Ho ho ho!" },
    { id: 'j5', title: 'Parallel Lines', text: "Parallel lines have so much in common. It's a shame they'll never meet! Hahaha!" },
    { id: 'j6', title: 'Flamingo', text: "Why do flamingos stand on one leg? Because if they lifted the other one, they'd fall over! Hee hee!" },
    { id: 'j7', title: 'Piano Hands', text: "What do you get when you drop a piano down a mine shaft? A flat minor! Bwahaha!" },
    { id: 'j8', title: 'Two Tired', text: "Why couldn't the bicycle stand up by itself? It was two tired! Hahaha!" },
    { id: 'j9', title: 'Zero to Eight', text: "What did the number 0 say to the number 8? Nice belt! Ho ho ho!" },
    { id: 'j10', title: 'Construction', text: "I'm reading a book on anti-gravity. It's impossible to put down! Hahaha!" },
    { id: 'j11', title: 'Math Book', text: "Why was the math book sad? Because it had too many problems. Boo hoo... just kidding! Hahaha!" },
    { id: 'j12', title: 'Wall Talk', text: "What did one wall say to the other? I'll meet you at the corner! Hee hee!" },
    { id: 'j13', title: 'Fake Noodle', text: "What do you call a fake noodle? An impasta! Hahaha!" },
    { id: 'j14', title: 'Paper Joke', text: "I would tell you a joke about paper, but it's tearable. Ho ho ho!" },
    { id: 'j15', title: 'Skeleton', text: "Why didn't the skeleton go to the party? He had no body to go with! Bwahaha!" },
    { id: 'j16', title: 'Cheese', text: "What do you call cheese that isn't yours? Nacho cheese! Hahaha!" },
    { id: 'j17', title: 'Light Bulb', text: "How many tickles does it take to make an octopus laugh? Ten tickles! Hee hee hee!" },
    { id: 'j18', title: 'Coffee', text: "Why did the coffee file a police report? It got mugged! Hahaha!" },
    { id: 'j19', title: 'Golfer', text: "Why did the golfer bring two pairs of pants? In case he got a hole in one! Ho ho ho!" },
    { id: 'j20', title: 'Orange', text: "Why did the orange stop? It ran out of juice! Hahaha!" },
    { id: 'j21', title: 'Tomato', text: "Why did the tomato turn red? Because it saw the salad dressing! Hee hee!" },
    { id: 'j22', title: 'Elsa', text: "Why can't you give Elsa a balloon? Because she will let it go! Hahaha!" },
    { id: 'j23', title: 'Musical', text: "Why did the cookie go to the hospital? Because he felt crummy! Ho ho!" },
    { id: 'j24', title: 'Astronaut', text: "Why did the astronaut break up with his girlfriend? He needed some space! Hahaha!" },
    { id: 'j25', title: 'Computer', text: "Why did the computer go to the doctor? It had a virus! Hee hee!" },
    { id: 'j26', title: 'Elevator', text: "I used to be a baker, but I couldn't make enough dough. Now I work at the bank! Hahaha!" },
    { id: 'j27', title: 'Bee', text: "What do you call a bee that can't make up its mind? A maybe! Ho ho ho!" },
    { id: 'j28', title: 'Pony', text: "I was going to tell a time-traveling joke, but you didn't like it. Hahaha!" },
    { id: 'j29', title: 'Nose', text: "Why is your nose in the middle of your face? Because it's the scenter! Hee hee!" },
    { id: 'j30', title: 'Plate', text: "What did one plate say to the other plate? Dinner is on me! Hahaha!" },
    { id: 'j31', title: 'Ocean', text: "What did the ocean say to the beach? Nothing, it just waved! Ho ho ho!" },
    { id: 'j32', title: 'Tree', text: "Why did the tree go to the dentist? It needed a root canal! Hahaha!" },
    { id: 'j33', title: 'Calendar', text: "Why was the calendar popular? Because it had a lot of dates! Hee hee!" },
    { id: 'j34', title: 'Moon', text: "Why did the moon skip dinner? It was full! Hahaha!" },
    { id: 'j35', title: 'Spider', text: "Why are spiders so smart? They can find everything on the web! Ho ho ho!" },
    { id: 'j36', title: 'Fish', text: "Where do fish keep their money? In the river bank! Hahaha!" },
    { id: 'j37', title: 'T-Rex', text: "Why can't a T-Rex clap its hands? Because it's extinct! Just kidding, short arms! Hee hee!" },
    { id: 'j38', title: 'Ghost', text: "What is a ghost's favorite fruit? Booberries! Hahaha!" },
    { id: 'j39', title: 'Vampire', text: "Why does a vampire brush his teeth? To prevent bat breath! Ho ho ho!" },
    { id: 'j40', title: 'Math', text: "Why is 6 afraid of 7? Because 7 8 9! Hahaha!" },
    { id: 'j41', title: 'Cookie', text: "What kind of key opens a banana? A mon-key! Hee hee!" },
    { id: 'j42', title: 'Dog', text: "What do you call a dog magician? A labracadabrador! Hahaha!" },
    { id: 'j43', title: 'Cat', text: "What is a cat's favorite color? Purr-ple! Ho ho ho!" },
    { id: 'j44', title: 'Cow', text: "What do you call a sleeping cow? A bulldozer! Hahaha!" },
    { id: 'j45', title: 'Pig', text: "What do you call a pig that does karate? A pork chop! Hee hee!" },
    { id: 'j46', title: 'Duck', text: "What time do ducks wake up? At the quack of dawn! Hahaha!" },
    { id: 'j47', title: 'Horse', text: "Why did the horse chew with his mouth open? Because he had bad stable manners! Ho ho!" },
    { id: 'j48', title: 'Bear', text: "What do you call a bear with no teeth? A gummy bear! Hahaha!" },
    { id: 'j49', title: 'Frog', text: "What is a frog's favorite drink? Croak-a-cola! Hee hee!" },
    { id: 'j50', title: 'Bird', text: "Why did the bird go to the hospital? To get a tweetment! Hahaha!" },
    { id: 'j51', title: 'Cloud', text: "What do you call a sheep with no legs? A cloud! Ho ho ho!" },
    { id: 'j52', title: 'Snowman', text: "What did one snowman say to the other? Do you smell carrots? Hahaha!" },
    { id: 'j53', title: 'Toilet', text: "Why did the toilet paper roll down the hill? To get to the bottom! Hee hee!" },
    { id: 'j54', title: 'Stairs', text: "Why do we tell actors to break a leg? Because every play has a cast! Hahaha!" },
    { id: 'j55', title: 'Balloon', text: "What kind of music do balloons hate? Pop music! Ho ho ho!" },
    { id: 'j56', title: 'Train', text: "How do trains hear? Through their engineers! Hahaha!" },
    { id: 'j57', title: 'Clock', text: "Why did the man sit on the clock? He wanted to be on time! Hee hee!" },
    { id: 'j58', title: 'Belt', text: "Can a kangaroo jump higher than a house? Of course, a house doesn't jump at all! Hahaha!" },
    { id: 'j59', title: 'Hat', text: "What did the hat say to the scarf? You hang around, I'll go on ahead! Ho ho ho!" },
    { id: 'j60', title: 'Shoe', text: "What kind of shoes do ninjas wear? Sneakers! Hahaha!" },
    { id: 'j61', title: 'Sock', text: "Why did the sock go to the doctor? It had a hole in it! Hee hee!" },
    { id: 'j62', title: 'Shirt', text: "Why did the shirt go to school? To get smarter! Hahaha!" },
    { id: 'j63', title: 'Pants', text: "Why did the pants go to the party? To get down! Ho ho ho!" },
    { id: 'j64', title: 'Glasses', text: "Why did the glasses go to the police? They were framed! Hahaha!" },
    { id: 'j65', title: 'Lamp', text: "Why did the lamp go to school? To get brighter! Hee hee!" },
    { id: 'j66', title: 'Table', text: "Why did the table go to the doctor? It had a broken leg! Hahaha!" },
    { id: 'j67', title: 'Chair', text: "Why did the chair go to the party? To sit down! Ho ho ho!" },
    { id: 'j68', title: 'Bed', text: "Why did the bed go to the doctor? It had a spring loose! Hahaha!" },
    { id: 'j69', title: 'Door', text: "Why did the door go to the doctor? It had a knob loose! Hee hee!" },
    { id: 'j70', title: 'Window', text: "Why did the window go to the doctor? It was in pane! Hahaha!" },
    { id: 'j71', title: 'Roof', text: "Why did the roof go to the doctor? It had a leak! Ho ho ho!" },
    { id: 'j72', title: 'Floor', text: "Why did the floor go to the doctor? It was board! Hahaha!" },
    { id: 'j73', title: 'Wall', text: "Why did the wall go to the doctor? It was plastered! Hee hee!" },
    { id: 'j74', title: 'Ceiling', text: "Why did the ceiling go to the doctor? It was cracking up! Hahaha!" },
    { id: 'j75', title: 'House', text: "Why did the house go to the doctor? It had a window pane! Ho ho ho!" },
    { id: 'j76', title: 'Car', text: "Why did the car go to the doctor? It had gas! Hahaha!" },
    { id: 'j77', title: 'Bus', text: "Why did the bus go to the doctor? It was tired! Hee hee!" },
    { id: 'j78', title: 'Truck', text: "Why did the truck go to the doctor? It had a flat tire! Hahaha!" },
    { id: 'j79', title: 'Bike', text: "Why did the bike go to the doctor? It was two tired! Ho ho ho!" },
    { id: 'j80', title: 'Plane', text: "Why did the plane go to the doctor? It had the flu! Hahaha!" },
    { id: 'j81', title: 'Boat', text: "Why did the boat go to the doctor? It was sinking! Hee hee!" },
    { id: 'j82', title: 'Ship', text: "Why did the ship go to the doctor? It was a wreck! Hahaha!" },
    { id: 'j83', title: 'Submarine', text: "Why did the submarine go to the doctor? It was under the weather! Ho ho ho!" },
    { id: 'j84', title: 'Rocket', text: "Why did the rocket go to the doctor? It was spaced out! Hahaha!" },
    { id: 'j85', title: 'Star', text: "Why did the star go to the doctor? It was burning up! Hee hee!" },
    { id: 'j86', title: 'Sun', text: "Why did the sun go to the doctor? It was too hot! Hahaha!" },
    { id: 'j87', title: 'Planet', text: "Why did the planet go to the doctor? It had no atmosphere! Ho ho ho!" },
    { id: 'j88', title: 'Galaxy', text: "Why did the galaxy go to the doctor? It was spiraling out of control! Hahaha!" },
    { id: 'j89', title: 'Universe', text: "Why did the universe go to the doctor? It was expanding! Hee hee!" },
    { id: 'j90', title: 'Black Hole', text: "Why did the black hole go to the doctor? It was sucking everything in! Hahaha!" },
    { id: 'j91', title: 'Alien', text: "Why did the alien go to the doctor? It was feeling green! Ho ho ho!" },
    { id: 'j92', title: 'Robot', text: "Why did the robot go to the doctor? It had a screw loose! Hahaha!" },
    { id: 'j93', title: 'Cyborg', text: "Why did the cyborg go to the doctor? It was feeling mechanical! Hee hee!" },
    { id: 'j94', title: 'Android', text: "Why did the android go to the doctor? It had a bug! Hahaha!" },
    { id: 'j95', title: 'Computer', text: "Why did the computer go to the doctor? It had a virus! Ho ho ho!" },
    { id: 'j96', title: 'Laptop', text: "Why did the laptop go to the doctor? It had a hard drive failure! Hahaha!" },
    { id: 'j97', title: 'Tablet', text: "Why did the tablet go to the doctor? It had a cracked screen! Hee hee!" },
    { id: 'j98', title: 'Phone', text: "Why did the phone go to the doctor? It had no signal! Hahaha!" },
    { id: 'j99', title: 'Watch', text: "Why did the watch go to the doctor? It was losing time! Ho ho ho!" },
    { id: 'j100', title: 'Clock', text: "Why did the clock go to the doctor? It was running slow! Hahaha!" },
    // Adult Satire - Marriage, Money, Job
    { id: 'j101', title: 'Marriage Workshop', text: "Marriage is a workshop... where the husband works and the wife shops! Just kidding! Hahaha!" },
    { id: 'j102', title: 'Boss Logic', text: "My boss told me to have a good day... so I went home! Hahaha!" },
    { id: 'j103', title: 'Budgeting', text: "I have enough money to last me the rest of my life... unless I buy something! Hee hee!" },
    { id: 'j104', title: 'Job Interview', text: "The interviewer asked: 'Where do you see yourself in 5 years?' I said: 'Celebrating the 5th anniversary of you asking me this question!' Ho ho ho!" },
    { id: 'j105', title: 'Retirement Plan', text: "My retirement plan is to find a wealthy spouse. Plan B is to win the lottery. Plan C is to keep working until I'm 90! Hahaha!" },
    { id: 'j106', title: 'Marriage Advice', text: "The secret to a happy marriage remains a secret! But laughter helps! Hee hee!" },
    { id: 'j107', title: 'Payday', text: "I love my job only when I'm on vacation... and on payday! Hahaha!" },
    { id: 'j108', title: 'Credit Card', text: "My credit card is like a teenager. It's always asking for money and I don't know where it goes! Ho ho ho!" },
    { id: 'j109', title: 'Teamwork', text: "Teamwork is essential... it allows you to blame someone else! Just kidding! Hahaha!" },
    { id: 'j110', title: 'Dieting', text: "I'm on a whiskey diet. I've lost three days already! Hee hee! Drink responsibly!" }
];

export const STORIES = [
    { id: 's1', title: 'Yoga Class', text: "I went to a Laughter Yoga class and forgot how to laugh! The instructor said, 'Fake it \'til you make it!' So I started making donkey noises. Hee-haw! Everyone joined in! We were a room full of happy donkeys! Hahaha!" },
    { id: 's2', title: 'Meditation Fail', text: "I tried to meditate today. I closed my eyes, took a deep breath... and fell asleep! I woke up laughing because my cat was sitting on my head! He he he! Best meditation ever!" },
    { id: 's3', title: 'Traffic Jam', text: "I was stuck in traffic for an hour. Instead of getting angry, I started singing opera to the other drivers. 'Oooooh Sole Mioooo!' The guy next to me started conducting! We had a whole concert on the highway! Hahaha!" },
    { id: 's4', title: 'Grocery Store', text: "I was at the grocery store and dropped a melon. It rolled all the way down the aisle like a bowling ball! I yelled 'Strike!' and everyone clapped! Ho ho ho! Who knew shopping could be a sport?" },
    { id: 's5', title: 'Zoom Call', text: "I was on a serious Zoom call and my parrot flew in. He landed on my shoulder and squawked, 'You're on mute!' right when I was talking! The whole team burst out laughing! Hee hee! He's the new manager now." },
    { id: 's6', title: 'Gym Mishap', text: "I went to the gym and tried the treadmill. I didn't know it was already on! I flew off the back like a superhero! I landed on a yoga ball and bounced right back up! Ta-da! Hahaha!" },
    { id: 's7', title: 'Cooking Disaster', text: "I tried to bake a cake. It came out looking like a flat tire! I put some frosting on it and called it a 'pancake surprise'. My family ate it and laughed! Ho ho ho! Tasted like rubber though!" },
    { id: 's8', title: 'Wrong Number', text: "I called the wrong number and started singing 'Happy Birthday'. The stranger on the other end sang along! We finished the whole song before I realized! Hahaha! Happy Birthday to whoever that was!" },
    { id: 's9', title: 'Elevator Pitch', text: "I was practicing my elevator pitch in an actual elevator. I got so excited I waved my hands and hit all the buttons! The elevator stopped at every floor! I made 10 new friends that day! Hee hee!" },
    { id: 's10', title: 'Dog Walk', text: "I was walking my dog and he saw a squirrel. He pulled so hard I started running! I tripped and rolled down a hill! My dog thought it was a game and rolled with me! We were a rolling ball of fur and laughter! Hahaha!" },
    { id: 's11', title: 'Rain Dance', text: "It started raining while I was waiting for the bus. Instead of hiding, I started dancing! A little kid joined me, then his mom, then the whole bus stop! We were the 'Rainy Day Dancers'! Ho ho ho!" },
    { id: 's12', title: 'Library Laugh', text: "I was in the library and read a funny joke. I tried to hold it in, but it came out as a loud snort! Everyone looked at me. I couldn't stop! Soon the librarian was giggling too! Shhh... Hahaha!" },
    { id: 's13', title: 'Karaoke Night', text: "I went to karaoke and sang 'I Will Survive'. I was so passionate I fell off the stage! I kept singing from the floor! The crowd went wild! I survived! Hee hee!" },
    { id: 's14', title: 'Haircut', text: "I tried to cut my own hair. I sneezed and cut a chunk out of my bangs! Now I look like a jagged rockstar! I'm rocking the 'Oops' look! Hahaha!" },
    { id: 's15', title: 'Ice Cream', text: "I bought an ice cream cone and it immediately fell on my shoe. I looked at it, looked at the sky, and just laughed! My shoe enjoyed the treat more than I did! Ho ho ho!" },
    { id: 's16', title: 'Beach Day', text: "I went to the beach and fell asleep. I woke up and a crab was stealing my sandwich! I chased him but he was too fast! Enjoy your lunch, Mr. Crab! Hahaha!" },
    { id: 's17', title: 'Cinema', text: "I went to the movies and sat in the wrong theater. I watched 20 minutes of a horror movie thinking it was a comedy! I was laughing while everyone else was screaming! Hee hee! Oops!" },
    { id: 's18', title: 'Park Bench', text: "I sat on a park bench that had 'Wet Paint' sign. I stood up with green stripes on my pants! I told everyone it's the new fashion! Zebra style! Hahaha!" },
    { id: 's19', title: 'Bus Ride', text: "I fell asleep on the bus and missed my stop. I woke up in a different city! I decided to explore and found the best pizza ever! Getting lost was the best plan! Ho ho ho!" },
    { id: 's20', title: 'Camping', text: "I went camping and forgot the tent. I slept under the stars... until it rained! I made a shelter out of leaves. I felt like a squirrel! Hahaha!" },
    { id: 's21', title: 'Skiing', text: "I went skiing and couldn't stop. I went down the hill backwards! Everyone thought I was a pro doing tricks! I was just terrified! Hee hee!" },
    { id: 's22', title: 'Painting', text: "I tried to paint a portrait of my cat. It looked like a potato with whiskers! My cat looked at it and hissed! Even he's an art critic! Hahaha!" },
    { id: 's23', title: 'Gardening', text: "I planted carrots and grew weeds! I have the best weed garden in the neighborhood! I'm selling 'organic artisanal greens'! Ho ho ho!" },
    { id: 's24', title: 'Knitting', text: "I tried to knit a scarf. It turned into a blanket! It's so long I can wrap my whole house in it! Cozy house! Hahaha!" },
    { id: 's25', title: 'Fishing', text: "I went fishing and caught... a boot! It was my size too! Now I just need to catch the other one! Hee hee!" },
    { id: 's26', title: 'Hiking', text: "I went hiking and got lost. I followed a butterfly for an hour! It led me right back to my car! Nature's GPS! Hahaha!" },
    { id: 's27', title: 'Picnic', text: "I had a picnic and a squirrel stole my apple. He sat in the tree and ate it while watching me! I hope you enjoyed the show, buddy! Ho ho ho!" },
    { id: 's28', title: 'Zoo', text: "I went to the zoo and a monkey mimicked me. I scratched my head, he scratched his. I danced, he danced! I found my twin! Hahaha!" },
    { id: 's29', title: 'Museum', text: "I sneezed in a quiet museum. It echoed like a cannon blast! A security guard said 'Bless you' over the intercom! Hee hee!" },
    { id: 's30', title: 'Concert', text: "I went to a concert and clapped on the wrong beat. The singer looked at me and smiled! I'm starting a new rhythm! Hahaha!" },
    { id: 's31', title: 'Wedding', text: "I went to a wedding and caught the bouquet. I'm already married! My husband looked terrified! Ho ho ho!" },
    { id: 's32', title: 'Birthday', text: "I blew out the candles on my cake and my false teeth flew out! They landed right in the frosting! Sweetest smile ever! Hahaha!" },
    { id: 's33', title: 'Halloween', text: "I dressed up as a ghost for Halloween. I used a dirty sheet! Everyone thought I was a pile of laundry! Scary laundry! Hee hee!" },
    { id: 's34', title: 'Christmas', text: "I wrapped a present and forgot what was inside. I opened it myself! It was socks! I was so surprised! Hahaha!" },
    { id: 's35', title: 'Easter', text: "I hid Easter eggs and forgot where. I found one in my shoe a month later! A smelly surprise! Ho ho ho!" },
    { id: 's36', title: 'Valentine', text: "I bought chocolates for my valentine... and ate them all on the way home! I gave her the empty box and a hug! Love is sweet! Hahaha!" },
    { id: 's37', title: 'New Year', text: "I made a resolution to stop eating chocolate. I lasted 5 minutes! New record! Hee hee!" },
    { id: 's38', title: 'Thanksgiving', text: "I burnt the turkey. We ordered pizza! Best Thanksgiving ever! Turkey pepperoni! Hahaha!" },
    { id: 's39', title: 'Vacation', text: "I packed for a tropical vacation. I arrived and it was snowing! I wore my swimsuit over my coat! Fashion trendsetter! Ho ho ho!" },
    { id: 's40', title: 'Road Trip', text: "We sang '99 Bottles of Beer' on a road trip. We lost count at 50 and started over! It was the never-ending song! Hahaha!" },
    { id: 's41', title: 'Flight', text: "I fell asleep on the plane and snored. The pilot announced 'Turbulence' just to wake me up! Hee hee!" },
    { id: 's42', title: 'Hotel', text: "I got locked out of my hotel room in my pajamas. I went to the lobby and had coffee! Pajama party! Hahaha!" },
    { id: 's43', title: 'Restaurant', text: "I ordered soup and ate it with a fork. It took a long time! I'm on a slow food diet! Ho ho ho!" },
    { id: 's44', title: 'Cafe', text: "I ordered a small coffee and got a bucket! I was vibrating for a week! Super energy! Hahaha!" },
    { id: 's45', title: 'Bar', text: "I walked into a bar... and bumped my head! It was a metal bar! Ouch! Hee hee!" },
    { id: 's46', title: 'Club', text: "I went dancing and did the 'Robot'. A real robot challenged me to a dance off! I won! Hahaha!" },
    { id: 's47', title: 'Party', text: "I arrived at the party a day early. I helped set up! I'm the best guest ever! Ho ho ho!" },
    { id: 's48', title: 'Date', text: "I went on a date and spilled water on my pants. I said 'I'm just so excited to see you!' We laughed all night! Hahaha!" },
    { id: 's49', title: 'Interview', text: "I went to a job interview and wore two different shoes. I said 'I'm versatile!' I got the job! Hee hee!" },
    { id: 's50', title: 'Work', text: "I sent a funny cat video to my boss instead of the report. He replied with a dog video! Best boss ever! Hahaha!" },
    { id: 's51', title: 'Meeting', text: "I fell asleep in a meeting and said 'Amen' when I woke up. Everyone thought I was praying! Ho ho ho!" },
    { id: 's52', title: 'Presentation', text: "I did a presentation with spinach in my teeth. Everyone was smiling at me! I thought I was doing great! Hahaha!" },
    { id: 's53', title: 'Office', text: "I brought donuts to the office and ate half of them on the way. I told them it was a 'quality control' check! Hee hee!" },
    { id: 's54', title: 'Commute', text: "I rode my bike to work and my pants ripped. I walked in backwards! Everyone thought I was moonwalking! Hahaha!" },
    { id: 's55', title: 'Lunch', text: "I packed a sandwich and forgot to put anything in it! I ate two slices of bread! Air sandwich! Ho ho ho!" },
    { id: 's56', title: 'Break', text: "I took a coffee break and spilled it on my keyboard. Now my computer types 'caffeine' automatically! Hahaha!" },
    { id: 's57', title: 'Deadline', text: "I finished a project a minute before the deadline. I felt like James Bond defusing a bomb! 007 of spreadsheets! Hee hee!" },
    { id: 's58', title: 'Promotion', text: "I got promoted and tripped on my way to the stage. I rolled up to the podium! That's how I roll! Hahaha!" },
    { id: 's59', title: 'Retirement', text: "I retired and bought a boat. I don't know how to sail! I just sit in the harbor and drink tea! Captain Relax! Ho ho ho!" },
    { id: 's60', title: 'School', text: "I raised my hand in class and forgot the answer. I just high-fived the air! Teacher thought I was stretching! Hahaha!" },
    { id: 's61', title: 'Exam', text: "I studied for the wrong exam. I wrote an essay about pizza instead of history! I got an A for creativity! Hee hee!" },
    { id: 's62', title: 'Recess', text: "I played tag and tagged a tree. The tree is now 'it'! Watch out! Hahaha!" },
    { id: 's63', title: 'Homework', text: "My dog actually ate my homework! I brought the dog to school as proof! He burped the alphabet! Ho ho ho!" },
    { id: 's64', title: 'Field Trip', text: "We went to a farm and a goat ate my map. We were lost in the corn maze for hours! Corn-fusing! Hahaha!" },
    { id: 's65', title: 'Science Fair', text: "I made a volcano and it exploded on the principal! He looked like a lava monster! I won first prize! Hee hee!" },
    { id: 's66', title: 'Talent Show', text: "I told jokes at the talent show and nobody laughed. I started laughing at myself! Then everyone laughed! Contagious! Hahaha!" },
    { id: 's67', title: 'Prom', text: "I stepped on my date's dress. We both fell! We danced on the floor! Breakdancing champions! Ho ho ho!" },
    { id: 's68', title: 'Graduation', text: "I threw my cap in the air and it got stuck in a tree. I'm still waiting for it to come down! High hopes! Hahaha!" },
    { id: 's69', title: 'College', text: "I lived on instant noodles for a year. I turned into a noodle! I'm flexible now! Hee hee!" },
    { id: 's70', title: 'Dorm', text: "I did laundry and turned all my clothes pink. I'm the Pink Panther now! Stylish! Hahaha!" },
    { id: 's71', title: 'Roommate', text: "My roommate talks in his sleep. We have full conversations! He agreed to do the dishes! Ho ho ho!" },
    { id: 's72', title: 'Professor', text: "My professor wore mismatched socks. I pointed it out. He said 'I have another pair just like this at home!' Hahaha!" },
    { id: 's73', title: 'Library', text: "I fell off my chair in the library. I played it off like I was looking for a book on the floor! Smooth! Hee hee!" },
    { id: 's74', title: 'Cafeteria', text: "I slipped on a banana peel. Classic! I took a bow! Comedy gold! Hahaha!" },
    { id: 's75', title: 'Gym', text: "I got stuck in a yoga pose. The instructor had to untangle me! I'm a human pretzel! Ho ho ho!" },
    { id: 's76', title: 'Pool', text: "I did a belly flop. I emptied the pool! Tsunami alert! Hahaha!" },
    { id: 's77', title: 'Track', text: "I ran a race and ran the wrong way. I won the race to the parking lot! Hee hee!" },
    { id: 's78', title: 'Football', text: "I caught the ball and scored a touchdown... for the other team! Oops! Hahaha!" },
    { id: 's79', title: 'Basketball', text: "I tried to dunk and got stuck on the rim. Just hanging out! Ho ho ho!" },
    { id: 's80', title: 'Baseball', text: "I swung the bat and hit the catcher. Sorry! Foul ball! Hahaha!" },
    { id: 's81', title: 'Soccer', text: "I tripped over the ball. I invented a new move! The 'Stumble Dribble'! Hee hee!" },
    { id: 's82', title: 'Tennis', text: "I hit the ball over the fence. Home run! Wrong sport! Hahaha!" },
    { id: 's83', title: 'Golf', text: "I hit the ball into the water. I went swimming to get it! Golf and swim! Ho ho ho!" },
    { id: 's84', title: 'Bowling', text: "I threw the ball backwards. I got a strike on the vending machine! Free snacks! Hahaha!" },
    { id: 's85', title: 'Skating', text: "I went ice skating and hugged the wall. I cleaned the whole rink! Human mop! Hee hee!" },
    { id: 's86', title: 'Skiing', text: "I hit a jump and lost my skis. I flew like an eagle! Landed like a turkey! Hahaha!" },
    { id: 's87', title: 'Surfing', text: "I tried to surf and the board hit me. I fought the board and the board won! Ho ho ho!" },
    { id: 's88', title: 'Camping', text: "A bear ate my marshmallows. We shared a campfire! He tells good stories! Hahaha!" },
    { id: 's89', title: 'Fishing', text: "I caught a fish and it slapped me. Rude! I threw it back! Hee hee!" },
    { id: 's90', title: 'Hunting', text: "I went hunting and saw a deer. We stared at each other. I blinked first! He won! Hahaha!" },
    { id: 's91', title: 'Garden', text: "I watered the plants with juice. They grew sticky! Sweet flowers! Ho ho ho!" },
    { id: 's92', title: 'Mowing', text: "I mowed the lawn and mowed over the hose. Instant sprinkler system! Hahaha!" },
    { id: 's93', title: 'Painting', text: "I painted the room and painted myself into a corner. I had to wait for it to dry! Hee hee!" },
    { id: 's94', title: 'Plumbing', text: "I fixed the sink and flooded the kitchen. Indoor pool! Hahaha!" },
    { id: 's95', title: 'Electrician', text: "I changed a lightbulb and spun the whole ladder. Helicopter ride! Ho ho ho!" },
    { id: 's96', title: 'Carpenter', text: "I built a shelf and it was crooked. It's 'abstract art'! Hahaha!" },
    { id: 's97', title: 'Mechanic', text: "I fixed the car and had parts left over. Weight reduction! Hee hee!" },
    { id: 's98', title: 'Doctor', text: "I played doctor and put band-aids on the furniture. The sofa is healing nicely! Hahaha!" },
    { id: 's99', title: 'Nurse', text: "I took my temperature and it was 100. I got an A+ in health! Ho ho ho!" },
    { id: 's100', title: 'Dentist', text: "I brushed my teeth with shaving cream. I was foaming at the mouth! Rabies! Hahaha!" },
    // Adult Satire - Real Life
    { id: 's101', title: 'Online Shopping', text: "I bought a 'one size fits all' shirt online. It didn't fit! I guess I'm not 'all'! I'm 'extra'! Hahaha!" },
    { id: 's102', title: 'Gym Membership', text: "I have a gym membership. I pay $50 a month to feel guilty about not going! It's a guilt subscription! Hee hee!" },
    { id: 's103', title: 'House Cleaning', text: "I cleaned my house for 2 hours. Then I sat down for 5 minutes and it's messy again! Did the dust have a party? Hahaha!" },
    { id: 's104', title: 'Cooking Dinner', text: "I tried to cook a fancy dinner for my spouse. I set off the smoke alarm! We had 'Smoke Alarm Surprise' for dinner! It was burnt toast! Ho ho ho!" },
    { id: 's105', title: 'Tech Support', text: "I called tech support and they asked if my computer was plugged in. I said 'No, I'm wireless!' They hung up! Hahaha!" },
    { id: 's106', title: 'Parenting', text: "My kids asked me what it's like to be an adult. I told them it's like doing homework that never ends... and you have to pay for it! Hee hee!" },
    { id: 's107', title: 'Traffic', text: "I was late for work and told my boss 'Traffic was terrible!'. He said 'You live across the street!'. I said 'There was a lot of foot traffic in the hallway!' Hahaha!" },
    { id: 's108', title: 'Grocery List', text: "I went to the store for milk. I came back with 5 bags of chips, ice cream, and no milk! I'm banned from shopping alone! Ho ho ho!" },
    { id: 's109', title: 'DIY Project', text: "I tried to fix the leak in the sink. Now I have a fountain in the kitchen! Very fancy! Hahaha!" },
    { id: 's110', title: 'Alarm Clock', text: "My alarm clock is jealous of my relationship with my bed. It tries to break us up every morning! I hit it! Snooze button abuse! Hee hee!" }
];
